= Solr Ref Guide in Asciidoc
:toc:

toc::[]

This project is a proof of concept to evaluate changing the Apache Solr Ref Guide from being managed as a Confluence wiki to text files committed as part of Solr source code. HTML pages and PDFs could be generated using a publishing toolchain that is integrated with existing Solr/Lucene build processes.

This README describes the reasons for the change, what this POC demonstrates, and a short introduction on how to work with the recommended markdown format. Links are provided to additional information in this project's wiki.

== What's in this Repo?
This repo is a proof-of-concept for converting the Ref Guide to Asciidoc format. It includes:

* The current ref guide exported to HTML format (on 31 August 2015), and converted to Asciidoc format, in the `confluence-export` directory.
* Scripts to support converting from Confluence to Asciidoc format (more below).
* A few sample pages from the conversion with some additional cleanup, in the `asciidoc` directory.
* A sample `build.xml` to generate HTML and PDF versions of the sample pages.
* Scripts to assist with PDF generation.
* Sample HTML and PDF files with preliminary design included.

== How to Build

This project includes `ant` targets for building HTML and PDF versions of the Ref Guide.

* `ant doc` builds the HTML files by finding all `.adoc` files from `asciidoc` directory and making an HTML file for each page. It downloads a .jar file as a dependency. This only requires Ant.
* `ant pdf2` builds a PDF from the files defined in `asciidoc/book.adoc`. It builds a .jar file that is needed as a dependency before generating the PDF file. Maven is required to get all the dependencies to compile the .jar.

== Details and TODOs

NOTE: Some details have been moved into the wiki attached to this repo.

== Open Questions

=== Location of Source

At the outset, we recommend keeping the source in a different SVN tree from the main Lucene/Solr code. This will allow for a publication process separate from the release process. Over time, we would like the source for the docs to be co-located with Solr's source.

=== Organization of Files

How should we organize the Ref Guide pages in the directory tree?

* As chapters, with a folder for each main subject heading.
* As one big directory of files.

Some examples of how others have done it:

* HBase
** Source code: https://github.com/apache/hbase/tree/master/src/main/asciidoc
** Production book: http://hbase.apache.org/book.html
** JIRA for discussion to transition to HBase: https://issues.apache.org/jira/browse/HBASE-11533

* Eclipse Project Handbook
** Source code: http://git.eclipse.org/c/www.eclipse.org/projects.git/tree/handbook/source
** Production: http://www.eclipse.org/projects/handbook/

* Pro Git book
** Source code: https://github.com/progit/progit2
** Production: http://git-scm.com/book/en/v2

* CouchDB book (O'Reilly)
** Source code: not available publicly
** Production: http://guide.couchdb.org/editions/1/en/index.html

* Clojure Cookbook (O'Reilly)
** Source code: https://github.com/clojure-cookbook/clojure-cookbook
** Production: http://clojure-cookbook.com/ (link to purchase)

* Asciidoctor.org website:
** Source code: https://github.com/asciidoctor/asciidoctor.org
** Production: http://asciidoctor.org

For a much longer list, see https://github.com/asciidoctor/asciidoctor.org/issues/270.

=== Build Process

Asciidoctor is a toolchain written in Ruby which facilitates converting text files to other formats for publishing. One sub-project is the `asciidoctor-ant` plugin for Apache Ant.

==== HTML

Uses `asciidoctor-ant` plugin to convert to HTML. To generate HTML, simply run `ant doc`.

This task sets the output format, defines a custom stylesheet (see Styles, below), and defines the plugin to use for code syntax highlighting, and other parameters.

See <<wiki/BuildDetails.asciidoc, Build Details>> for more information on the HTML output task.

Still To Do:

* Determine where to put the pages online. See also section on <<Publishing Options>>.

==== PDF

===== Current Behavior

Currently the `ant pdf` target calls a script `pdf/scripts/createPDF.sh` which relies on the `asciidoctor-pdf` gem to be installed on the local machine.

To install this gem locally, follow these steps:

. `gem install --pre asciidoctor-pdf`
. `gem install coderay`

The second step installs the plugin that provides code syntax highlighting (Pygments is better IMO, but is not supported by `asciidoctor-ant` at this time.)

See https://github.com/asciidoctor/asciidoctor-pdf for more details on using this plugin.

*Issues*
It seems `asciidoctor-ant` should be able to handle the PDF conversion, but it doesn't.

Another plugin `asciidoctor-pdf` allows conversion direct to PDF, although this is a gem? It also has other dependencies, I think. Can it be a jar, like `asciidoctor-ant`?


=== Publication Bugs

There are some known issues that may impact our ability to convert documents as we want:

* Possibly an issue with pipe characters inside literal blocks in tables: https://github.com/asciidoctor/asciidoctor/issues/1421. Unclear if we have any of these.



=== Publishing Options

. Host in ASF CMS with website.
. Host however the javadocs are hosted.

==== Static Site Generators

Site generators allow creation of complex templates such as navigation menus and Javascript-based comments (like the Apache comment system, described more below).

No matter where the content is hosted, we should use a static site generator such as Jekyll, JBake, Awestruck & similar to generate the HTML pages.

Jekyll has a lot of attention these days, but is Ruby-based and it's not easy to see how it and it's dependencies would fit with the current Solr build process. Or even how to make it work with Ant.

http://www.jbake.org/[JBake] is Java-based, and touts itself as the "Jekyll of the JVM".

Both of these options require each document to contain a metadata header, which includes the page title and status (such as "published", "draft", etc.).

A downside to both options is they are primarily designed for blog posts, which is a slightly different paradigm than online documentation.

=== Comments

See <<wiki/Comments.asciidoc,Comments>> in this repo's wiki for details on how to handle comments in this structure.

=== Search

How will we provide search?

Recommend probably indexing generated HTML pages. Could use bin/post from Solr to recurse over the HTML files and index them.

Will need to figure out where to host Solr.


== How to Write Asciidoc
