= Solr Ref Guide in Asciidoc
:toc:

toc::[]

This project is a proof of concept to evaluate changing the Apache Solr Ref Guide from being managed as a Confluence wiki to text files committed as part of Solr source code. HTML pages and PDFs could be generated using a publishing toolchain that is integrated with existing Solr/Lucene build processes.

This README describes the reasons for the change, what this POC demonstrates, and a short introduction on how to work with the recommended markdown format.

== Proof of Concept Ref Guide

=== What's in this Repo?
This repo is a proof-of-concept for converting the Ref Guide to Asciidoc format. It includes:

* The currrent ref guide exported to HTML format (on 31 August 2015), and converted to Asciidoc format, in the `confluence-export` directory.
* Scripts to support converting from Confluence to Asciidoc format (more below).
* A few sample pages from the conversion with some additional cleanup, in the `asciidoc` directory.
* A sample `build.xml` to generate HTML and PDF versions of the sample pages.
* Scripts to assist with PDF generation.
* Sample HTML and PDF files with preliminary design included.

=== How to Build

This project includes `ant` targets for building HTML and PDF versions of the Ref Guide.

* `ant doc` builds the HTML files by finding all `.adoc` files from `asciidoc` directory and making an HTML file for each page. It downloads a .jar file as a dependency. This only requires Ant.
* `ant pdf2` builds a PDF from the files defined in `asciidoc/book.adoc`. It builds a .jar file that is needed as a dependency before generating the PDF file. Maven is required to get all the dependencies to compile the .jar.

== Why Change?

* Confluence is a wiki, and is primarily focused on team collaboration. In earlier releases, simplicity of content authoring was a focus (i.e., when it supported wiki markup language), but collaboration features are increasingly taking precedence over ease of use. These are not necessarily bad for Solr, but the editing experience has suffered.

* The presentation of the content is problematic and complex. While it’s simple to override the default stylesheets, the divs and classes are not clearly identified and change at random with updates.

* The presentation of text cannot be separated from the writing of the content. While editing a page, users must think about how the tables will lay out, how code boxes will appear, etc. Each of these items are barriers for non-Confluence experts to contribute to the documentation.

* Documentation is divorced from the code, creating another barrier for keeping documentation up-to-date when code changes occur. An alternative option could be to include the documentation with the source code repository; patches could include documentation updates with the code changes.

* Versioning the online version of the guide is problematic. The only way Confluence supports versioning is to create copies of each "space" for each release. This adds to the maintenance burden for producing the Ref Guide, which is already taxed around the time of each release. We could instead use the existing versioning system currently used for Lucene and Solr Javadocs. If the publication process is integrated with the build process, instead of developing a new process, we could use the existing process.

=== Why Asciidoc and Asciidoctor

Asciidoc is a lightweight text markup format which is similar to Markdown, but which has a broader range of markup notations for article and book publishing purposes.

The original asciidoc format has been extended and enhanced by a text processor and publishing toolchain called Asciidoctor.

[quote, What is Asciidoc?, asciidoctor.org]
____
So why do we struggle to write documents?

The main reason we struggle is because we don’t write documents the same way we write e-mail. Instead, we allow ourselves to get distracted by complex word processors, bury the content in XML schemas like DocBook, or battle with finicky WYSIWYG editors. How did we get ourselves into this mess?
____

More reasons at http://asciidoctor.org/docs/what-is-asciidoc/.


== Details and TODOs
This section describes the process for converting the Ref Guide from Confluence and open issues to be done or discussed.


=== Content Conversion Process
Confluence content has been converted with the following process:

* Export in HTML from Confluence
* Lucidworks conversion ant tasks found in `confluence-export/conversion-tools/jsoup/build.xml`:
** Clean up confluence styles (`ant scrape`)
** Add document hierarchy as links to each page (`ant map` then `ant hier`)
* Pandocs for html -> asciidoc conversion

Once the pages have been converted, they need some additional cleanup:

* Pandocs uses asciidoc conventions, some of which are simplified and extended with asciidoctor. For consistency, these should be modified:
** Headings in asciidoc use `~` and `^` symbols to indicate levels, while Asciidoctor uses multiple equal signs `=` to indicate the level (the number of equal signs is the heading level). The equal sign approach is more straightforward and readable when editing pages.
** Code example boxes are defined in asciidoc by multiple hyphens in a row before and after the example, Asciidoctor uses 4 hyphens.
** <more to come>
* Images exported out of Confluence have arcane naming and an odd directory structure. We should make the effort to clean those up in a consolidated image directory with human-readable names.

It's important to note that conversion of content may be a time- and labor-intensive process, but is only required once.

=== Location of Source

At the outset, we recommend keeping the source in a different SVN tree from the main Lucene/Solr code. This will allow for a publication process separate from the release process. Over time, we would like the source for the docs to be co-located with Solr's source.

=== Organization of Files

How should we organize the Ref Guide pages in the directory tree?

* As chapters, with a folder for each main subject heading.
* As one big directory of files.

Some examples of how others have done it:

* HBase
** Source code: https://github.com/apache/hbase/tree/master/src/main/asciidoc
** Production book: http://hbase.apache.org/book.html
** JIRA for discussion to transition to HBase: https://issues.apache.org/jira/browse/HBASE-11533

* Eclipse Project Handbook
** Source code: http://git.eclipse.org/c/www.eclipse.org/projects.git/tree/handbook/source
** Production: http://www.eclipse.org/projects/handbook/

* Pro Git book
** Source code: https://github.com/progit/progit2
** Production: http://git-scm.com/book/en/v2

* CouchDB book (O'Reilly)
** Source code: not available publicly
** Production: http://guide.couchdb.org/editions/1/en/index.html

* Clojure Cookbook (O'Reilly)
** Source code: https://github.com/clojure-cookbook/clojure-cookbook
** Production: http://clojure-cookbook.com/ (link to purchase)

* Asciidoctor.org website:
** Source code: https://github.com/asciidoctor/asciidoctor.org
** Production: http://asciidoctor.org

For a much longer list, see https://github.com/asciidoctor/asciidoctor.org/issues/270.

=== Build Process

Asciidoctor is a toolchain written in Ruby which facilitates converting text files to other formats for publishing. One sub-project is the `asciidoctor-ant` plugin for Apache Ant.

==== HTML

Uses `asciidoctor-ant` plugin to convert to HTML. To generate HTML, simply run `ant doc`.

This task sets the output format, defines a custom stylesheet (see Styles, below), and defines the plugin to use for code syntax highlighting, and other parameters.

===== HTML-related Rules in build.xml

The first part gets the required JAR file.

[source,xml]
----
<get src="http://repo1.maven.org/maven2/org/asciidoctor/asciidoctor-ant/1.5.1/asciidoctor-ant-1.5.1.jar"
  dest="lib/asciidoctor-ant.jar" usetimestamp="true"/>
----

The second part defines the rules for converting the documents to HTML.

[source,xml]
----
<target name="doc">
  <taskdef uri="antlib:org.asciidoctor.ant" resource="org/asciidoctor/ant/antlib.xml" classpath="lib/asciidoctor-ant.jar"/>
  <asciidoctor:convert
               sourceDirectory="asciidoc"
               outputDirectory="html"
               backend="html5"
               extensions="asc"
               sourceHighlighter="coderay"
               embedAssets="true"
               imagesDir="asciidoc/images">
    <attribute key="docinfo1" value='' />
    <attribute key="stylesheet" value="ref-guide.css" />
    <attribute key="stylesdir" value="html/styles" />
    <attribute key="icons" value="font" />
    <attribute key="figure-caption!" value='' />
    <attribute key="toc" value="right" />
 </asciidoctor:convert>
</target>
----

Still To Do:

* Determine where to put the pages online. See also section on <<Publishing Options>>.

==== PDF

===== Current Behavior

Currently the `ant pdf` target calls a script `pdf/scripts/createPDF.sh` which relies on the `asciidoctor-pdf` gem to be installed on the local machine.

To install this gem locally, follow these steps:

. `gem install --pre asciidoctor-pdf`
. `gem install coderay`

The second step installs the plugin that provides code syntax highlighting (Pygments is better IMO, but is not supported by `asciidoctor-ant` at this time.)

See https://github.com/asciidoctor/asciidoctor-pdf for more details on using this plugin.

*Issues*
It seems `asciidoctor-ant` should be able to handle the PDF conversion, but it doesn't.

Another plugin `asciidoctor-pdf` allows conversion direct to PDF, although this is a gem? It also has other dependencies, I think. Can it be a jar, like `asciidoctor-ant`?


=== Publication Bugs

There are some known issues that may impact our ability to convert documents as we want:

* Possibly an issue with pipe characters inside literal blocks in tables: https://github.com/asciidoctor/asciidoctor/issues/1421. Unclear if we have any of these.

=== Styling

==== HTML
The `ant html` task applies a custom stylesheet found in `html/styles/ref-guide.css`. This is an adaptation of the default Asciidoc stylesheet.

Some items still to do:

* Update styles for Solr branding.

==== PDF

PDF styles are driven by themes, which are defined in YAML files. The current theme is found in `pdf/themes/refguide-theme.yml`. The command to generate the PDF must include the theme directory and theme name or it will fall back to the default theme.

The default theme has been modified to update the font colors. Some items still to do:

* Proper headers and footers
* Title page with appropriate ASF branding
* Light gray highlight on inline monospace

Instructions on how to modify the theme are found in the https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc[Asciidoctor PDF Theming Guide].

=== Publishing Options

. Host in ASF CMS with website.
. Host however the javadocs are hosted.

==== Static Site Generators

Site generators allow creation of complex templates such as navigation menus and Javascript-based comments (like the Apache comment system, described more below).

No matter where the content is hosted, we should use a static site generator such as Jekyll, JBake, Awestruck & similar to generate the HTML pages.

Jekyll has a lot of attention these days, but is Ruby-based and it's not easy to see how it and it's dependencies would fit with the current Solr build process. Or even how to make it work with Ant.

http://www.jbake.org/[JBake] is Java-based, and touts itself as the "Jekyll of the JVM".

Both of these options require each document to contain a metadata header, which includes the page title and status (such as "published", "draft", etc.).

A downside to both options is they are primarily designed for blog posts, which is a slightly different paradigm than online documentation.

=== Comments

A key feature of today's cwiki setup is the ability for users to comment on errors or inconsistencies with the current content. The ASF has a comment system that can be implemented.

*Adding Comments to Pages*

Comments are added by including a JavaScript snippet on each page, which points to the ASF comment system with a unique page ID.

The snippet is available at (must login): https://comments.apache.org/panel.lua?site=solrcwiki&view=snippet&uid=741d0acac05816701215f891d97c8b451fe320b5).

Because this needs a page ID, and must be added to the generated HTML, there is an open question about how to insert the snippet during the production process. Some options:

* It can be easily added to the footer of the page, but that is suboptimal.
* Use a static site generator (Jekyll, JBake, Awestruck, etc.) that generates the whole site for a web server. Preferred would be to add this after the `<body>` but before the `<footer>`.
* Develop a post-processor for the publication process. Asciidoctor has general support for this, but none available that do specifically what we want. The closest might be the Google Analytics PostProcessor: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/google-analytics-postprocessor.rb

*Managing Comments*

The ASF comment system stores comments based on page ID. Every page that includes this ID will show the same comments. This allows us two options for incorporating comments:

. The same page across versions have the same ID (such as, "Language-Analysis"), so all versions of the page for each version will show the same comments.
.. Pro: comments are always in the same place.
.. Con: old comments may not be relevant to later changes.
. The same page across versions have unique IDs (such as, "Language-Analysis-5.3", "Language-Analysis-5.4", etc.), so each version of the page has comments only for that individual page/version.
.. Pro: comments are specific to the version.
.. Con: comments are spread across pages.

=== Search

How will we provide search?

Recommend probably indexing generated HTML pages. Could use bin/post from Solr to recurse over the HTML files and index them.

Will need to figure out where to host Solr.


== How to Write Asciidoc

=== Asciidoc Syntax

TBD.

In the meantime, take a look at http://asciidoctor.org/docs/user-manual/.

=== Asciidoctor Tools

TBD.
