= About This Guide
:page-shortname: about-this-guide
:page-permalink: about-this-guide.html

This guide describes all of the important features and functions of Apache Solr. It is free to download from http://lucene.apache.org/solr/.

Designed to provide high-level documentation, this guide is intended to be more encyclopedic and less of a cookbook. It is structured to address a broad spectrum of needs, ranging from new developers getting started to well-experienced developers extending their application or troubleshooting. It will be of use at any point in the application life cycle, for whenever you need authoritative information about Solr.

The material as presented assumes that you are familiar with some basic search concepts and that you can read XML. It does not assume that you are a Java programmer, although knowledge of Java is helpful when working directly with Lucene or when developing custom extensions to a Lucene/Solr installation.

[[AboutThisGuide-SpecialInlineNotes]]
=== Special Inline Notes

Special notes are included throughout these pages.

// TODO: This table has cells that won't work with PDF: https://github.com/ctargett/refguide-asciidoc-poc/issues/13

[width="100%",cols="50%,50%",options="header",]
|===
|Note Type |Look & Description
|*Information* a|
[NOTE]
====

Notes with a blue background are used for information that is important for you to know.

====

|*Notes* a|
[IMPORTANT]
====

Yellow notes are further clarifications of important points to keep in mind while using Solr.

====

|*Tip* a|
[TIP]
====

Notes with a green background are Helpful Tips.

====

|*Warning* a|
[WARNING]
====

Notes with a red background are warning messages.

====

|===

[[AboutThisGuide-HostsandPortExamples]]
=== Hosts and Port Examples

The default port when running Solr is 8983. The samples, URLs and screenshots in this guide may show different ports, because the port number that Solr uses is configurable. If you have not customized your installation of Solr, please make sure that you use port 8983 when following the examples, or configure your own installation to use the port numbers shown in the examples. For information about configuring port numbers, see <<managing-solr.adoc#managing-solr,Managing Solr>>.

Similarly, URL examples use 'localhost' throughout; if you are accessing Solr from a location remote to the server hosting Solr, replace 'localhost' with the proper domain or IP where Solr is running.

[[AboutThisGuide-Paths]]
=== Paths

Path information is given relative to `solr.home`, which is the location under the main Solr installation where Solr's collections and their `conf` and `data` directories are stored. When running the various examples mentioned through out this tutorial (i.e., `bin/solr -e techproducts`) the `solr.home` will be a sub directory of `example/` created for you automatically.
