= Postings Highlighter
:page-shortname: postings-highlighter
:page-permalink: postings-highlighter.html

PostingsHighlighter focuses on good document summaries and efficiency, but is less flexible than the other highlighters. It uses significantly less disk space, and provides a performant approach if queries have a low number of terms relative to the number of results per page. However, the drawbacks are that it is not a query matching debugger (it focuses on fast highlighting for full-text search) and it does not allow broken analysis chains.

To use this highlighter, you must turn on `storeOffsetsWithPositions` for the field. There is no need to turn on `termVectors`, `termPositions`, or `termOffsets` in fields since this highlighter does not make use of term vectors.

[[PostingsHighlighter-ConfiguringPostingsHighlighter]]
== Configuring Postings Highlighter

The configuration for the Postings Highlighter is done in `solrconfig.xml`.

First, define the search component:

[source,xml]
----
<searchComponent class="solr.HighlightComponent" name="highlight">
  <highlighting class="org.apache.solr.highlight.PostingsSolrHighlighter"/>
</searchComponent>
----

Note in this example, we have named the search component "highlight". If you started with a default `solrconfig.xml` file, then you already have a component with that name. You should either replace the default with this example, or rename the search component that is already there so there is no confusion about which search component implementation Solr should use.

Then in the request handler, you can define the defaults, as in this example:

[source,xml]
----
<requestHandler name="standard" class="solr.StandardRequestHandler">
  <lst name="defaults">
    <int name="hl.snippets">1</int>
    <str name="hl.tag.pre">&lt;em&gt;</str>
    <str name="hl.tag.post">&lt;/em&gt;</str>
    <str name="hl.tag.ellipsis">... </str>
    <bool name="hl.defaultSummary">true</bool>
    <str name="hl.encoder">simple</str>
    <float name="hl.score.k1">1.2</float>
    <float name="hl.score.b">0.75</float>
    <float name="hl.score.pivot">87</float>
    <str name="hl.bs.language"></str>
    <str name="hl.bs.country"></str>
    <str name="hl.bs.variant"></str>
    <str name="hl.bs.type">SENTENCE</str>
    <int name="hl.maxAnalyzedChars">10000</int>
  </lst>
</requestHandler>
----

This example shows all of the defaults for each parameter. If you intend to keep all of the defaults, you would not need to add anything to the request handler and could override the default values at query time as needed.

[[PostingsHighlighter-PostingsHighlighterParameters]]
== Postings Highlighter Parameters

The table below describes Solr's parameters for this highlighter. These parameters can be set as defaults (as in the examples), or the default values can be changed in the request handler or at query time. Most of the parameters can be specified per-field (exceptions noted below).

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Parameter |Default |Description
|hl |blank (no highlight) |When set to **true**, enables highlighted snippets to be generated in the query response. If set to *false* or to a blank or missing value, disables highlighting.
|hl.q |blank |Specifies an overriding query term for highlighting. If `hl.q` is specified, the highlighter will use that term rather than the main query term.
|hl.fl |blank |Specifies a list of fields to highlight. Accepts a comma- or space-delimited list of fields for which Solr should generate highlighted snippets. If left blank, highlights the defaultSearchField (or the field specified the `df` parameter if used) for the StandardRequestHandler. For the DisMaxRequestHandler, the `qf` fields are used as defaults. +
 +
A '*' can be used to match field globs, such as 'text_*' or even '*' to highlight on all fields where highlighting is possible. When using '*', consider adding `hl.requireFieldMatch=true`.
|hl.snippets |1 |Specifies maximum number of highlighted snippets to generate per field. It is possible for any number of snippets from zero to this value to be generated. This parameter accepts per-field overrides.
|hl.tag.pre |<em> |Specifies the text that should appear before a highlighted term.
|hl.tag.post |</em> |Specifies the text that should appear after a highlighted term.
|hl.tag.ellipsis |"... " |Specifies the text that should join two unconnected passages in the resulting snippet.
|hl.maxAnalyzedChars |10000 |Specifies the number of characters into a document that Solr should look for suitable snippets. This parameter does not accept per-field overrides.
|hl.multiValuedSeparatorChar |" " (space) |Specifies the logical separator between multi-valued fields.
|hl.defaultSummary |true |If **true**, a field should have a default summary if highlighting finds no matching passages.
|hl.encoder |simple |Defines the encoding for the resulting snippet. The value *simple* applies no escaping, while *html* will escape HTML characters in the text.
|hl.score.k1 |1.2 |Specifies BM25 term frequency normalization parameter 'k1'. For example, it can be set to "0" to rank passages solely based on the number of query terms that match.
|hl.score.b |0.75 |Specifies BM25 length normalization parameter 'b'. For example, it can be set to "0" to ignore the length of passages entirely when ranking.
|hl.score.pivot |87 |Specifies BM25 average passage length in characters.
|hl.bs.language |blank |Specifies the breakiterator language for dividing the document into passages.
|hl.bs.country |blank |Specifies the breakiterator country for dividing the document into passages.
|hl.bs.variant |blank |Specifies the breakiterator variant for dividing the document into passages.
|hl.bs.type |SENTENCE |Specifies the breakiterator type for dividing the document into passages. Can be **SENTENCE**, **WORD**, **CHARACTER**, **LINE**, or **WHOLE**.
|===

[[PostingsHighlighter-RelatedContent]]
== Related Content

* http://wiki.apache.org/solr/PostingsHighlighter[PostingsHighlighter] from the Solr wiki
* {solr-javadocs}/solr-core/org/apache/solr/highlight/PostingsSolrHighlighter.html[PostingsSolrHighlighter javadoc]
