= Solr Glossary
:page-shortname: solr-glossary
:page-permalink: solr-glossary.html

Where possible, terms are linked to relevant parts of the Solr Reference Guide for more information.

'''''

*Jump to a letter:*

<<SolrGlossary-A,A>> <<SolrGlossary-B,B>> <<SolrGlossary-C,C>> <<SolrGlossary-D,D>> <<SolrGlossary-E,E>> <<SolrGlossary-F,F>> G H <<SolrGlossary-I,I>> J K <<SolrGlossary-L,L>> <<SolrGlossary-M,M>> <<SolrGlossary-N,N>> <<SolrGlossary-O,O>> P <<SolrGlossary-Q,Q>> <<SolrGlossary-R,R>> <<SolrGlossary-S,S>> <<SolrGlossary-T,T>> U V <<SolrGlossary-W,W>> X Y <<SolrGlossary-Z,Z>>

[[SolrGlossary-A]]
== A

[[SolrGlossary-Atomicupdates]]
====== <<updating-parts-of-documents.adoc#UpdatingPartsofDocuments-AtomicUpdates,Atomic updates>>

An approach to updating only one or more fields of a document, instead of reindexing the entire document.

[[SolrGlossary-B]]
== B

[[SolrGlossary-Booleanoperators]]
====== Boolean operators

These control the inclusion or exclusion of keywords in a query by using operators such as AND, OR, and NOT.

[[SolrGlossary-C]]
== C

[[SolrGlossary-Cluster]]
====== Cluster

In Solr, a cluster is a set of Solr nodes operating in coordination with each other via <<SolrGlossary-ZooKeeper,ZooKeeper>>, and managed as a unit. A cluster may contain many collections. See also <<SolrGlossary-SolrCloud,SolrCloud>>.

[[SolrGlossary-Collection]]
====== Collection

In Solr, one or more <<SolrGlossary-Document,Documents>> grouped together in a single logical index using a single configuration and Schema. In <<SolrGlossary-SolrCloud,SolrCloud>> a collection may be divided up into multiple logical shards, which may in turn be distributed across many nodes, or in a Single node Solr installation, a collection may be a single <<SolrGlossary-Core,Core>>.

[[SolrGlossary-Commit]]
====== Commit

To make document changes permanent in the index. In the case of added documents, they would be searchable after a __commit__.

[[SolrGlossary-Core]]
====== Core

An individual Solr instance (represents a logical index). Multiple cores can run on a single node. See also <<SolrGlossary-SolrCloud,SolrCloud>>.

[[SolrGlossary-Corereload]]
====== Core reload

To re-initialize a Solr core after changes to `schema.xml`, `solrconfig.xml` or other configuration files.

[[SolrGlossary-D]]
== D

[[SolrGlossary-Distributedsearch]]
====== Distributed search

Distributed search is one where queries are processed across more than one <<SolrGlossary-Shard,shard>>.

[[SolrGlossary-Document]]
====== Document

A group of <<SolrGlossary-Field,fields>> and their values. Documents are the basic unit of data in a <<SolrGlossary-Collection,collection>>. Documents are assigned to <<SolrGlossary-Shard,shards>> using standard hashing, or by specifically assigning a shard within the document ID. Documents are versioned after each write operation.

[[SolrGlossary-E]]
== E

[[SolrGlossary-Ensemble]]
====== Ensemble

A <<SolrGlossary-ZooKeeper,ZooKeeper>> term to indicate multiple ZooKeeper instances running simultaneously and in coordination with each other for fault tolerance.

[[SolrGlossary-F]]
== F

[[SolrGlossary-Facet]]
====== Facet

The arrangement of search results into categories based on indexed terms.

[[SolrGlossary-Field]]
====== Field

The content to be indexed/searched along with metadata defining how the content should be processed by Solr.

[[SolrGlossary-I]]
== I

// OLD_CONFLUENCE_ID: SolrGlossary-Inversedocumentfrequency(IDF)

[[SolrGlossary-Inversedocumentfrequency_IDF_]]
====== Inverse document frequency (IDF)

A measure of the general importance of a term. It is calculated as the number of total Documents divided by the number of Documents that a particular word occurs in the collection. See http://en.wikipedia.org/wiki/Tf-idf and {lucene-javadocs}/core/org/apache/lucene/search/similarities/TFIDFSimilarity.html[the Lucene TFIDFSimilarity javadocs] for more info on TF-IDF based scoring and Lucene scoring in particular. See also <<SolrGlossary-Termfrequency,#Term frequency>>.

[[SolrGlossary-Invertedindex]]
====== Inverted index

A way of creating a searchable index that lists every word and the documents that contain those words, similar to an index in the back of a book which lists words and the pages on which they can be found. When performing keyword searches, this method is considered more efficient than the alternative, which would be to create a list of documents paired with every word used in each document. Since users search using terms they expect to be in documents, finding the term before the document saves processing resources and time.

[[SolrGlossary-L]]
== L

[[SolrGlossary-Leader]]
====== Leader

A single <<SolrGlossary-Replica,Replica>> for each <<SolrGlossary-Shard,Shard>> that takes charge of coordinating index updates (document additions or deletions) to other replicas in the same shard. This is a transient responsibility assigned to a node via an election, if the current Shard Leader goes down, a new node will automatically be elected to take its place. See also <<SolrGlossary-SolrCloud,SolrCloud>>.

[[SolrGlossary-M]]
== M

[[SolrGlossary-Metadata]]
====== Metadata

Literally, __data about data__. Metadata is information about a document, such as its title, author, or location.

[[SolrGlossary-N]]
== N

[[SolrGlossary-Naturallanguagequery]]
====== Natural language query

A search that is entered as a user would normally speak or write, as in, "What is aspirin?"

[[SolrGlossary-Node]]
====== Node

A JVM instance running Solr. Also known as a Solr server.

[[SolrGlossary-O]]
== O

[[SolrGlossary-Optimisticconcurrency]]
====== <<updating-parts-of-documents.adoc#UpdatingPartsofDocuments-OptimisticConcurrency,Optimistic concurrency>>

Also known as "optimistic locking", this is an approach that allows for updates to documents currently in the index while retaining locking or version control.

[[SolrGlossary-Overseer]]
====== Overseer

A single node in <<SolrGlossary-SolrCloud,SolrCloud>> that is responsible for processing and coordinating actions involving the entire cluster. It keeps track of the state of existing nodes, collections, shards, and replicas, and assigns new replicas to nodes. This is a transient responsibility assigned to a node via an election, if the current Overseer goes down, a new node will be automatically elected to take its place. See also <<SolrGlossary-SolrCloud,SolrCloud>>.

[[SolrGlossary-Q]]
== Q

[[SolrGlossary-Queryparser]]
====== Query parser

A query parser processes the terms entered by a user.

[[SolrGlossary-R]]
== R

[[SolrGlossary-Recall]]
====== Recall

The ability of a search engine to retrieve _all_ of the possible matches to a user's query.

[[SolrGlossary-Relevance]]
====== Relevance

The appropriateness of a document to the search conducted by the user.

[[SolrGlossary-Replica]]
====== Replica

A <<SolrGlossary-Core,Core>> that acts as a physical copy of a <<SolrGlossary-Shard,Shard>> in a <<SolrGlossary-SolrCloud,SolrCloud>> <<SolrGlossary-Collection,Collection>>.

[[SolrGlossary-Replication]]
====== <<index-replication.adoc#index-replication,Replication>>

A method of copying a master index from one server to one or more "slave" or "child" servers.

[[SolrGlossary-RequestHandler]]
====== <<requesthandlers-and-searchcomponents-in-solrconfig.adoc#requesthandlers-and-searchcomponents-in-solrconfig,RequestHandler>>

Logic and configuration parameters that tell Solr how to handle incoming "requests", whether the requests are to return search results, to index documents, or to handle other custom situations.

[[SolrGlossary-S]]
== S

[[SolrGlossary-SearchComponent]]
====== <<requesthandlers-and-searchcomponents-in-solrconfig.adoc#requesthandlers-and-searchcomponents-in-solrconfig,SearchComponent>>

Logic and configuration parameters used by request handlers to process query requests. Examples of search components include faceting, highlighting, and "more like this" functionality.

[[SolrGlossary-Shard]]
====== Shard

In SolrCloud, a logical partition of a single <<SolrGlossary-Collection,Collection>>. Every shard consists of at least one physical <<SolrGlossary-Replica,Replica>>, but there may be multiple Replicas distributed across multiple <<SolrGlossary-Nodes,Nodes>> for fault tolerance. See also <<SolrGlossary-SolrCloud,SolrCloud>>.

[[SolrGlossary-SolrCloudSolrCloud_32604293.html]]
====== <<solrcloud.adoc#solrcloud,SolrCloud>>

Umbrella term for a suite of functionality in Solr which allows managing a <<SolrGlossary-Cluster,Cluster>> of Solr <<SolrGlossary-Nodes,Nodes>> for scalability, fault tolerance, and high availability.

// OLD_CONFLUENCE_ID: SolrGlossary-SolrSchema(managed-schemaorschema.xml)

[[SolrGlossary-SolrSchema_managed-schemaorschema.xml_]]
====== <<documents-fields-and-schema-design.adoc#documents-fields-and-schema-design,Solr Schema (managed-schema or schema.xml)>>

The Solr index Schema defines the fields to be indexed and the type for the field (text, integers, etc.) By default schema data can be "managed" at run time using the <<schema-api.adoc#schema-api,Schema API>> and is typically kept in a file named `managed-schema` which Solr modifies as needed, but a collection may be configured to use a static Schema, which is only loaded on startup from a human edited configuration file - typically named `schema.xml`. See <<schema-factory-definition-in-solrconfig.adoc#schema-factory-definition-in-solrconfig,Schema Factory Definition in SolrConfig>> for details.

// OLD_CONFLUENCE_ID: SolrGlossary-SolrConfig(solrconfig.xml)

[[SolrGlossary-SolrConfig_solrconfig.xml_]]
====== <<the-well-configured-solr-instance.adoc#the-well-configured-solr-instance,SolrConfig (solrconfig.xml)>>

The Apache Solr configuration file. Defines indexing options, RequestHandlers, highlighting, spellchecking and various other configurations. The file, solrconfig.xml is located in the Solr home conf directory.

[[SolrGlossary-SpellCheck]]
====== <<spell-checking.adoc#spell-checking,Spell Check>>

The ability to suggest alternative spellings of search terms to a user, as a check against spelling errors causing few or zero results.

[[SolrGlossary-Stopwords]]
====== Stopwords

Generally, words that have little meaning to a user's search but which may have been entered as part of a <<SolrGlossary-Naturallanguagequery,natural language>> query. Stopwords are generally very small pronouns, conjunctions and prepositions (such as, "the", "with", or "and")

[[SolrGlossary-SuggesterSuggester_32604262.html]]
====== <<suggester.adoc#suggester,Suggester>>

Functionality in Solr that provides the ability to suggest possible query terms to users as they type.

[[SolrGlossary-Synonyms]]
====== Synonyms

Synonyms generally are terms which are near to each other in meaning and may substitute for one another. In a search engine implementation, synonyms may be abbreviations as well as words, or terms that are not consistently hyphenated. Examples of synonyms in this context would be "Inc." and "Incorporated" or "iPod" and "i-pod".

[[SolrGlossary-T]]
== T

[[SolrGlossary-Termfrequency]]
====== Term frequency

The number of times a word occurs in a given document. See http://en.wikipedia.org/wiki/Tf-idf and {lucene-javadocs}/core/org/apache/lucene/search/similarities/TFIDFSimilarity.html[the Lucene TFIDFSimilarity javadocs] for more info on TF-IDF based scoring and Lucene scoring in particular. See also <<SolrGlossary-Inversedocumentfrequency_IDF_,#Inverse document frequency (IDF)>>.

[[SolrGlossary-Transactionlog]]
====== Transaction log

An append-only log of write operations maintained by each <<SolrGlossary-Replica,Replica>>. This log is required with SolrCloud implementations and is created and managed automatically by Solr.

[[SolrGlossary-W]]
== W

[[SolrGlossary-Wildcard]]
====== Wildcard

A wildcard allows a substitution of one or more letters of a word to account for possible variations in spelling or tenses.

[[SolrGlossary-Z]]
== Z

[[SolrGlossary-ZooKeeper]]
====== ZooKeeper

Also known as http://zookeeper.apache.org/[Apache ZooKeeper]. The system used by SolrCloud to keep track of configuration files and node names for a cluster. A ZooKeeper cluster is used as the central configuration store for the cluster, a coordinator for operations requiring distributed synchronization, and the system of record for cluster topology. See also <<SolrGlossary-SolrCloud,SolrCloud>>.
