1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]
3.  link:Using-the-Solr-Administration-User-Interface.html[Using the Solr Administration User Interface]
4.  link:Core-Specific-Tools.html[Core-Specific Tools]

32604180
--------

The Plugins screen shows information and statistics about Solr's status and performance. You can find information about the performance of Solr's caches, the state of Solr's searchers, and the configuration of searchHandlers and requestHandlers.

Choose an area of interest on the right, and then drill down into more specifics by clicking on one of the names that appear in the central part of the window. In this example, we've chosen to look at the Searcher stats, from the Core area:

_Searcher Statistics_

The display is a snapshot taken when the page is loaded. You can get updated status by choosing to either *Watch Changes* or **Refresh Values**. Watching the changes will highlight those areas that have changed, while refreshing the values will reload the page with updated information.
