= Authentication and Authorization Plugins
:page-shortname: authentication-and-authorization-plugins
:page-permalink: authentication-and-authorization-plugins.html
:page-children: basic-authentication-plugin, kerberos-authentication-plugin, rule-based-authorization-plugin

Solr has security frameworks for supporting authentication and authorization of users. This allows for verifying a user's identity and for restricting access to resources in a Solr cluster. Solr includes plugins to support Basic authentication, Kerberos, and rule-based authorization of users. Additional plugins can be developed using the authentication and authorization frameworks described below.

The plugin implementation will dictate if the plugin can be used with Solr running in SolrCloud mode only or also if running in standalone mode. If the plugin supports SolrCloud only, a `security.json` file must be created and uploaded to ZooKeeper before it can be used. If the plugin also supports standalone mode, a system property `-DauthenticationPlugin=<pluginClassName>` can be used instead of creating and managing `security.json` in ZooKeeper. Here is a list of the available plugins and the approach supported:

* <<basic-authentication-plugin.adoc#,Basic authentication>>: SolrCloud only.
* <<kerberos-authentication-plugin.adoc#,Kerberos authentication>>: SolrCloud or standalone mode.
* <<rule-based-authorization-plugin.adoc#,Rule-based authorization>>: SolrCloud only.

The following section describes how to enable plugins with `security.json` in ZooKeeper when using Solr in SolrCloud mode.

[[AuthenticationandAuthorizationPlugins-EnablePluginswithsecurity.json]]
== Enable Plugins with security.json

All of the information required to initialize either type of security plugin is stored in a `/security.json` file in ZooKeeper. This file contains 2 sections, one each for authentication and authorization.

*security.json*

[source,java]
----
{
  "authentication" : {
    "class": "class.that.implements.authentication"
  },
  "authorization": {
    "class": "class.that.implements.authorization"
  }
}
----

The `/security.json` file needs to be in ZooKeeper before a Solr instance comes up so Solr starts with the security plugin enabled. See the section <<AuthenticationandAuthorizationPlugins-Addingsecurity.jsontoZookeeper,Adding security.json to Zookeeper>> below for information on how to do this.

Depending on the plugin(s) in use, other information will be stored in `security.json` such as user information or rules to create roles and permissions. This information is added through the APIs for each plugin provided by Solr, or, in the case of a custom plugin, the approach designed by you.

Here is a more detailed `security.json` example. In this, the Basic authentication and rule-based authorization plugins are enabled, and some data has been added:

[source,json]
----
{
"authentication":{
   "class":"solr.BasicAuthPlugin",
   "credentials":{"solr":"IV0EHq1OnNrj6gvRCwvFwTrZ1+z1oBbnQdiVC3otuq0= Ndd7LKvVBAaZIF0QAVi1ekCfAJXr1GGfLtRUXhgrF8c="}
},
"authorization":{
   "class":"solr.RuleBasedAuthorizationPlugin",
   "permissions":[{"name":"security-edit",
      "role":"admin"}]
   "user-role":{"solr":"admin"}
}}
----

[[AuthenticationandAuthorizationPlugins-Addingsecurity.jsontoZooKeeper]]
=== Adding security.json to ZooKeeper

While configuring Solr to use an authentication or authorization plugin, you will need to upload a `security.json` file to ZooKeeper as in the example below.

[source,bash]
----
> server/scripts/cloud-scripts/zkcli.sh -zkhost localhost:2181 -cmd put /security.json 
  '{"authentication": {"class": "org.apache.solr.security.KerberosPlugin"}}'
----

Note that this example defines the `KerberosPlugin` for authentication. You will want to modify this section as appropriate for the plugin you are using.

This example also defines `security.json` on the command line, but you can also define a file locally and upload it to ZooKeeper.

[WARNING]
====

Depending on the authentication and authorization plugin that you use, you may have user information stored in `security.json`. If so, we highly recommend that you implement access control in your ZooKeeper nodes. Information about how to enable this is available in the section <<zookeeper-access-control.adoc#,ZooKeeper Access Control>>.

====

[[AuthenticationandAuthorizationPlugins-Authentication]]
== Authentication

Authentication plugins help in securing the endpoints of Solr by authenticating incoming requests. A custom plugin can be implemented by extending the AuthenticationPlugin class.

An authentication plugin consists of two parts:

1.  Server-side component, which intercepts and authenticates incoming requests to Solr using a mechanism defined in the plugin, such as Kerberos, Basic Auth or others.
2.  Client-side component, i.e., an extension of `HttpClientConfigurer`, which enables a SolrJ client to make requests to a secure Solr instance using the authentication mechanism which the server understands.

[[AuthenticationandAuthorizationPlugins-EnablingaPlugin]]
=== Enabling a Plugin

* Specify the authentication plugin in `/security.json` as in this example:
+
*security.json*
+
[source,java]
----
{
  "authentication": {
    "class": "class.that.implements.authentication",
    "other_data" : "..."}
}
----
* All of the content in the authentication block of `security.json` would be passed on as a map to the plugin during initialization.
* An authentication plugin can also be used with a standalone Solr instance by passing in `-DauthenticationPlugin=<plugin class name>` during the startup.

[[AuthenticationandAuthorizationPlugins-AvailableAuthenticationPlugins]]
=== Available Authentication Plugins

Solr has two implementations of authentication plugins:

* <<kerberos-authentication-plugin.adoc#,Kerberos Authentication Plugin>>
* <<basic-authentication-plugin.adoc#,Basic Authentication Plugin>>

[[AuthenticationandAuthorizationPlugins-Authorization]]
== Authorization

An authorization plugin can be written for Solr by extending the http://lucene.apache.org/solr/6_1_0/solr-core/org/apache/solr/security/AuthorizationPlugin.html[AuthorizationPlugin] interface.

[[AuthenticationandAuthorizationPlugins-LoadingaCustomPlugin]]
=== Loading a Custom Plugin

* Make sure that the plug-in implementation is in the classpath.
* The plugin can then be initialized by specifying the same in `security.json` in the following manner:

*security.json*

[source,java]
----
{
  "authorization": {
    "class": "org.apache.solr.security.MockAuthorizationPlugin",
    "other_data" : "..."}
}
----

All of the content in the `authorization` block of `security.json` would be passed on as a map to the plugin during initialization.

[IMPORTANT]
====

The authorization plugin is only supported in SolrCloud mode. Also, reloading the plugin isn't supported at this point and requires a restart of the Solr instance (meaning, the JVM should be restarted, not simply a core reload).

====

[[AuthenticationandAuthorizationPlugins-AvailableAuthorizationPlugins]]
=== Available Authorization Plugins

Solr has one implementation of an authorization plugin:

* <<rule-based-authorization-plugin.adoc#,Rule-Based Authorization Plugin>>
