1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]
3.  link:Managing-Solr.html[Managing Solr]
4.  link:Securing-Solr.html[Securing Solr]
5.  link:Authentication-and-Authorization-Plugins.html[Authentication and Authorization Plugins]

Basic Authentication Plugin
---------------------------

Solr can support Basic authentication for users with the use of the BasicAuthPlugin

An authorization plugin is also available to configure Solr with permissions to perform various activities in the system. Once activated, access to the Solr Admin UI and all requests will need to be authenticated and users will be required to have the proper authorization for all requests, including using the Admin UI and making any API calls. The authorization plugin is described in the section link:Rule-Based-Authorization-Plugin.html[Rule-Based Authorization Plugin].

[[BasicAuthenticationPlugin-EnableBasicAuthentication]]
Enable Basic Authentication
~~~~~~~~~~~~~~~~~~~~~~~~~~~

To use Basic authentication, you must first create a `security.json` file and store it in ZooKeeper. This file and how to upload it to ZooKeeper is described in detail in the section link:Authentication-and-Authorization-Plugins.html#AuthenticationandAuthorizationPlugins-EnabledPluginswithsecurity.json[Enable Plugins with security.json].

For Basic authentication, the `security.json` file must have an `authentication` part which defines the class being used for authentication. Usernames and passwords (as a sha256(password+salt) hash) could be added when the file is created, or can be added later with the Basic authentication API, described below.

The `authorization` part is not related to Basic authentication, but is a separate authorization plugin designed to support fine-grained user access control. For more information, see link:Rule-Based-Authorization-Plugin.html[Rule-Based Authorization Plugin].

An example `security.json` showing both sections is shown below to show how these plugins can work together:

---------------------------------------------------------------------------------------------------------------------
{
"authentication":{
   "class":"solr.BasicAuthPlugin",
   "credentials":{"solr":"IV0EHq1OnNrj6gvRCwvFwTrZ1+z1oBbnQdiVC3otuq0= Ndd7LKvVBAaZIF0QAVi1ekCfAJXr1GGfLtRUXhgrF8c="}
},
"authorization":{
   "class":"solr.RuleBasedAuthorizationPlugin",
   "permissions":[{"name":"security-edit",
      "role":"admin"}]
   "user-role":{"solr":"admin"},
}}
---------------------------------------------------------------------------------------------------------------------

There are several things defined in this file:

* Basic authentication and rule-based authorization plugins are enabled.
* A user called 'solr', with a password has been defined.
* The 'admin' role has been defined, and it has permission to edit security settings.
* The 'solr' user has been defined to the 'admin' role.

[[BasicAuthenticationPlugin-Caveats]]
Caveats
~~~~~~~

There are a few things to keep in mind when using the Basic authentication plugin.

* Credentials are sent in plain text by default. It's recommended to use SSL for communication when Basic authentication is enabled, as described in the section link:Enabling-SSL.html[Enabling SSL].
* A user who has access to write permissions to `security.json` will be able to modify all the permissions and how users have been assigned permissions. Special care should be taken to only grant access to editing security to appropriate users.
* Your network should, of course, be secure. Even with Basic authentication enabled, you should not unnecessarily expose Solr to the outside world.

[[BasicAuthenticationPlugin-EditingUserDetails]]
Editing User Details
~~~~~~~~~~~~~~~~~~~~

An Authentication API allows modifying user IDs and passwords. The API provides an endpoint with specific commands to set user details or delete a user.

[[BasicAuthenticationPlugin-APIEntryPoint]]
API Entry Point
+++++++++++++++

`admin/authentication`

This endpoint is not collection-specific, so users are created for the entire Solr cluster. If users need to be restricted to a specific collection, that can be done with the authorization rules.

[[BasicAuthenticationPlugin-AddaUserorEditaPassword]]
Add a User or Edit a Password
+++++++++++++++++++++++++++++

The `set-user` command allows you to add users and change their passwords. For example, the following defines two users and their passwords:

-------------------------------------------------------------------------------------------------------------------
curl --user solr:SolrRocks http://localhost:8983/solr/admin/authentication -H 'Content-type:application/json'-d '{ 
  "set-user": {"tom" : "TomIsCool" , 
               "harry":"HarrysSecret"}}'
-------------------------------------------------------------------------------------------------------------------

[[BasicAuthenticationPlugin-DeleteaUser]]
Delete a User
+++++++++++++

The `delete-user` command allows you to remove a user. The user password does not need to be sent to remove a user. In the following example, we've asked that user IDs 'tom' and 'harry' be removed from the system.

-------------------------------------------------------------------------------------------------------------------
curl --user solr:SolrRocks http://localhost:8983/solr/admin/authentication -H 'Content-type:application/json'-d  '{
 "delete-user": ["tom","harry"]}'
-------------------------------------------------------------------------------------------------------------------

Note:

For enabling a SolrJ client to communicate with a Solr cluster secured with Basic authentication, please instantiate your own `HttpClient` (and configure it using a `UsernamePasswordCredentials` to pass on your credentials) and use it while creating the `SolrClient`. Details on how to use Basic authentication using `HttpClient` can be found here: http://hc.apache.org/httpcomponents-client-ga/tutorial/html/authentication.html.
