1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]
3.  link:Using-the-Solr-Administration-User-Interface.html[Using the Solr Administration User Interface]

Cloud Screens
-------------

When running in SolrCloud mode, an option will appear in the Admin UI between Logging and Core Admin for Cloud. It's not possible at the current time to manage the nodes of the SolrCloud cluster from the Admin UI, but you can view them and open the Solr Admin UI on each node to view the status and statistics for the node and each core on each node.

Only Visible When using SolrCloud

Note:

The "Cloud" menu option is only available on Solr instances running in link:Getting-Started-with-SolrCloud.html[SolrCloud mode]. Single node or master/slave replication instances of Solr will not display this option.

Click on the Cloud option in the left-hand navigation, and a small sub-menu appears with options called "Tree", "Graph", "Graph (Radial)" and "Dump". The default view ("Graph") shows a graph of each collection, the shards that make up those collections, and the addresses of each replica for each shard. This example shows the very simple two-node, two-shard, two-replica cluster you can get running the "`bin/solr -e cloud`" example:

The "Graph (Radial)" option provides a different visual view of each node. Using the same example cluster, the radial graph view looks like:

The "Tree" option shows a directory structure of the files in ZooKeeper, including `clusterstate.json`, configuration files, and other status and information files. In this example, we show the leader definition for "shard1" in the "gettingstarted" collection:

The final option is "Dump", which allows you to download an XML file with all the ZooKeeper configuration files.
