Documents, Fields, and Schema Design
====================================
:page-shortname: documents-fields-and-schema-design
:page-permalink: documents-fields-and-schema-design.html
:page-children: overview-of-documents-fields-and-schema-design, solr-field-types, defining-fields, copying-fields, dynamic-fields, other-schema-elements, schema-api, putting-the-pieces-together, docvalues, schemaless-mode

This section discusses how Solr organizes its data into documents and fields, as well as how to work with a schema in Solr.

This section includes the following topics:

<<overview-of-documents-fields-and-schema-design.adoc#,Overview of Documents, Fields, and Schema Design>>: An introduction to the concepts covered in this section.

<<solr-field-types.adoc#,Solr Field Types>>: Detailed information about field types in Solr, including the field types in the default Solr schema.

<<defining-fields.adoc#,Defining Fields>>: Describes how to define fields in Solr.

<<copying-fields.adoc#,Copying Fields>>: Describes how to populate fields with data copied from another field.

<<dynamic-fields.adoc#,Dynamic Fields>>: Information about using dynamic fields in order to catch and index fields that do not exactly conform to other field definitions in your schema.

<<schema-api.adoc#,Schema API>>: Use curl commands to read various parts of a schema or create new fields and copyField rules.

<<other-schema-elements.adoc#,Other Schema Elements>>: Describes other important elements in the Solr schema.

<<putting-the-pieces-together.adoc#,Putting the Pieces Together>>: A higher-level view of the Solr schema and how its elements work together.

<<docvalues.adoc#,DocValues>>: Describes how to create a docValues index for faster lookups.

<<schemaless-mode.adoc#,Schemaless Mode>>: Automatically add previously unknown schema fields using value-based field type guessing.
