1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]

Getting Started
---------------

Solr makes it easy for programmers to develop sophisticated, high-performance search applications with advanced features such as faceting (arranging search results in columns with numerical counts of key terms). Solr builds on another open source search technology: Lucene, a Java library that provides indexing and search technology, as well as spellchecking, hit highlighting and advanced analysis/tokenization capabilities. Both Solr and Lucene are managed by the Apache Software Foundation (http://www.apache.org/[www.apache.org)].

The Lucene search library currently ranks among the top 15 open source projects and is one of the top 5 Apache projects, with installations at over 4,000 companies. Lucene/Solr downloads have grown nearly ten times over the past three years, with a current run-rate of over 6,000 downloads a day. The Solr search server, which provides application builders a ready-to-use search platform on top of the Lucene search library, is the fastest growing Lucene sub-project. Apache Lucene/Solr offers an attractive alternative to the proprietary licensed search and discovery software vendors.

This section helps you get Solr up and running quickly, and introduces you to the basic Solr architecture and features. It covers the following topics:

link:Installing-Solr.html[Installing Solr]: A walkthrough of the Solr installation process.

link:Running-Solr.html[Running Solr]: An introduction to running Solr. Includes information on starting up the servers, adding documents, and running queries.

link:A-Quick-Overview.html[A Quick Overview]: A high-level overview of how Solr works.

link:A-Step-Closer.html[A Step Closer]: An introduction to Solr's home directory and configuration options.

link:Solr-Start-Script-Reference.html[Solr Start Script Reference]: a complete reference of all of the commands and options available with the bin/solr script.
