Indexing and Basic Data Operations
==================================
:page-shortname: indexing-and-basic-data-operations
:page-permalink: indexing-and-basic-data-operations.html
:page-children: introduction-to-solr-indexing, post-tool, uploading-data-with-index-handlers, uploading-data-with-solr-cell-using-apache-tika, uploading-structured-data-store-data-with-the-data-import-handler, updating-parts-of-documents, detecting-languages-during-indexing, de-duplication, content-streams, uima-integration

This section describes how Solr adds data to its index. It covers the following topics:

* **<<introduction-to-solr-indexing.adoc#,Introduction to Solr Indexing>>**: An overview of Solr's indexing process.

* **<<post-tool.adoc#,Post Tool>>**: Information about using `post.jar` to quickly upload some content to your system.

* **<<uploading-data-with-index-handlers.adoc#,Uploading Data with Index Handlers>>**: Information about using Solr's Index Handlers to upload XML/XSLT, JSON and CSV data.

* **<<uploading-data-with-solr-cell-using-apache-tika.adoc#,Uploading Data with Solr Cell using Apache Tika>>**: Information about using the Solr Cell framework to upload data for indexing.

* **<<uploading-structured-data-store-data-with-the-data-import-handler.adoc#,Uploading Structured Data Store Data with the Data Import Handler>>**: Information about uploading and indexing data from a structured data store.

* **<<updating-parts-of-documents.adoc#,Updating Parts of Documents>>**: Information about how to use atomic updates and optimistic concurrency with Solr.

* **<<detecting-languages-during-indexing.adoc#,Detecting Languages During Indexing>>**: Information about using language identification during the indexing process.

* **<<de-duplication.adoc#,De-Duplication>>**: Information about configuring Solr to mark duplicate documents as they are indexed.

* **<<content-streams.adoc#,Content Streams>>**: Information about streaming content to Solr Request Handlers.

* **<<uima-integration.adoc#,UIMA Integration>>**: Information about integrating Solr with Apache's Unstructured Information Management Architecture (UIMA). UIMA lets you define custom pipelines of Analysis Engines that incrementally add metadata to your documents as annotations.

[[IndexingandBasicDataOperations-IndexingUsingClientAPIs]]
=== Indexing Using Client APIs

Using client APIs, such as <<using-solrj.adoc#,SolrJ>>, from your applications is an important option for updating Solr indexes. See the <<client-apis.adoc#,Client APIs>> section for more information.
