1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]
3.  link:Managing-Solr.html[Managing Solr]
4.  link:Securing-Solr.html[Securing Solr]
5.  link:Authentication-and-Authorization-Plugins.html[Authentication and Authorization Plugins]

Kerberos Authentication Plugin
------------------------------

The Kerberos authentication plugin can be used to secure a Solr cluster using an existing Kerberos infrastructure.

[[KerberosAuthenticationPlugin-Prerequisites]]
Prerequisites
^^^^^^^^^^^^^

* The plugin information must be provided in `/security.json` before the Solr instances are started. The authentication plugin implementation to be used can also be specified during the node startup using the following parameter: `-DauthenticationPlugin=org.apache.solr.security.KerberosPlugin`.
* Each Solr node must have a service principal, i.e., a Kerberos username, which is registered with the Key Distribution Center (KDC) and is used to authenticate incoming requests. An example of a service principal is `HTTP/host1@YOUR-DOMAIN.ORG`, where `HTTP` indicates the type of requests which this service principal will be used to authenticate, `host1` is the host name of the machine hosting the Solr node, `YOUR-DOMAIN.ORG` is the organization wide Kerberos realm. The `HTTP/` in the service principal is a must for SPNego to work with requests to Solr over HTTP. Multiple Solr nodes on the same host may have the same service principal, since the host name is common to them all.
* Along with the service principal, each Solr node needs a keytab file which should contain the credentials of the service principal used. A keytab file contains encrypted credentials to support passwordless logins while obtaining Kerberos tickets from the KDC. For a Solr node, the keytab file should be kept at a secure location and not shared with users of the cluster.
* Since a Solr cluster requires internode communication, each node must also be able to make Kerberos enabled requests to other nodes. For this, each Solr node also requires to have a client principal and a corresponding keytab file. It is fine for the client principal to be the same as the service principal.

[[KerberosAuthenticationPlugin-KerberizedZooKeeper]]
Kerberized ZooKeeper
^^^^^^^^^^^^^^^^^^^^

When setting up a kerberized Solr cluster, it is recommended to enable Kerberos security for Zookeeper as well. In such a setup, the client principal used to authenticate its requests with Zookeeper can be shared for internode communication as well. This has the benefit of not needing to renew the TGTs separately, since the Zookeeper client used by Solr takes care of this. To achieve this, a single JAAS configuration (with the app name as Client ) can be used for the Kerberos plugin as well as for the Zookeeper client. See the example section below for an example on starting Zookeeper in Kerberos mode.

[[KerberosAuthenticationPlugin-StartupParameters]]
Startup Parameters
^^^^^^^^^^^^^^^^^^

While starting up Solr, the following host-specific parameters need to be passed.

[cols=",,",options="header",]
|===============================================================================================================================================================================================================
|Parameter Name |Required |Description
|solr.kerberos.name.rules |No |Used to map Kerberos principals to short names. Default value is `DEFAULT`. Example of a name rule: `RULE:[1:$1@$0](.*EXAMPLE.COM)s/@.*// `
|solr.kerberos.cookie.domain |Yes |Used to issue cookies and should have the hostname of the Solr node.
|solr.kerberos.principal. |Yes |The service principal.
|solr.kerberos.keytab |Yes |Keytab file path containing service principal credentials.
|solr.kerberos.jaas.appname |No |The app name (section name) within the JAAS config file which is required for internode communication. Default is `Client`, which is used for Zookeeper authentication as well.
|java.security.auth.login.config |Yes |Path to a JAAS config file for configuring a Solr client for internode communication.
|===============================================================================================================================================================================================================

KDC with AES-256 encryption

Note:

If your KDC uses AES-256 encryption, you need to add the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files to your JRE before a kerberized Solr can interact with the KDC. For Java 1.7, this is available here: http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html.

[[KerberosAuthenticationPlugin-Example]]
Example
~~~~~~~

This example walks through setting up Solr and ZooKeeper to use Kerberos for authentication.

[[KerberosAuthenticationPlugin-Step#1:SettingupZooKeeper]]
Step#1: Setting up ZooKeeper
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1.  Start a kerberos enabled ZooKeeper. While starting up ZooKeeper, pass the following parameter pointing to a JAAS configuration file:
+
------------------------------------------------------------
-Djava.security.auth.login.config=/home/foo/jaas-client.conf
------------------------------------------------------------
+
To do that, create a file `java.env` in ZooKeepers' conf directory and add:
+
---------------------------------------------------------------------------------
export JVMFLAGS="-Djava.security.auth.login.config=/etc/zookeeper/conf/jaas.conf"
---------------------------------------------------------------------------------
+
This JAAS configuration file should contain the following (change your principal and keytab path as suitable):
+
------------------------------------------------------
Server {
 com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  keyTab=/keytabs/zkhost1.keytab
  storeKey=true
  doNotPrompt=true
  useTicketCache=false
  debug=true
  principal=”zookeeper/host1”;
}
------------------------------------------------------
+
Also, Add the following lines to the ZooKeeper configuration file zoo.cfg:
+
--------------------------------------------------------------------------
authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
jaasLoginRenew=3600000
--------------------------------------------------------------------------
+
Refer to Step #2 (below) on how to create a principal and keytab for Zookeeper.
2.  Set up Solr to use the Kerberos plugin by uploading the `security.json` as follows:
+
----------------------------------------------------------------------------------------------------------------------------------------------------------------
> server/scripts/cloud-scripts/zkcli.sh -zkhost localhost:2181 -cmd put /security.json '{"authentication":{"class": "org.apache.solr.security.KerberosPlugin"}}'
----------------------------------------------------------------------------------------------------------------------------------------------------------------

Note:

If you already have a `/security.json` file in Zookeeper, download the file, add or modify the authentication section and upload it back to ZooKeeper.

[[KerberosAuthenticationPlugin-Step#2:Addingprincipalandgeneratingthekeytabfile]]
Step #2: Adding principal and generating the keytab file
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1.  At the KDC server, create a Kerberos principal for each Solr host and generate a keytab file as follows. This example assumes the hostname is `192.168.0.7` and your home directory is `/home/foo/`. This example should be modified for your own environment.
+
-----------------------------------------------------------------------------------------------------------------------------------
root@kdc:/# kadmin.local 
Authenticating as principal foo/admin@EXAMPLE.COM with password.

kadmin.local:  addprinc HTTP/192.168.0.107
WARNING: no policy specified for HTTP/192.168.0.107@EXAMPLE.COM; defaulting to no policy
Enter password for principal "HTTP/192.168.0.107@EXAMPLE.COM":
Re-enter password for principal "HTTP/192.168.0.107@EXAMPLE.COM":
Principal "HTTP/192.168.0.107@EXAMPLE.COM" created.

kadmin.local:  ktadd -k /tmp/107.keytab HTTP/192.168.0.107
Entry for principal HTTP/192.168.0.107 with kvno 2, encryption type aes256-cts-hmac-sha1-96 added to keytab WRFILE:/tmp/107.keytab.
Entry for principal HTTP/192.168.0.107 with kvno 2, encryption type arcfour-hmac added to keytab WRFILE:/tmp/107.keytab.
Entry for principal HTTP/192.168.0.107 with kvno 2, encryption type des3-cbc-sha1 added to keytab WRFILE:/tmp/108.keytab.
Entry for principal HTTP/192.168.0.107 with kvno 2, encryption type des-cbc-crc added to keytab WRFILE:/tmp/107.keytab.

kadmin.local:  quit
-----------------------------------------------------------------------------------------------------------------------------------
2.  Copy the keytab file from the KDC server’s `/tmp/107.keytab` location to the Solr host at `/keytabs/107.keytab`.

You might need to do the same for the Zookeeper service principal and keytab for Step #1.

[[KerberosAuthenticationPlugin-Step#3:Settingthehostspecificparameters]]
Step #3: Setting the host specific parameters
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Add the following lines to the `bin/solr.in.sh`. Make sure to change this example to use the right hostname and the keytab file path.

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SOLR_AUTHENTICATION_CLIENT_CONFIGURER=org.apache.solr.client.solrj.impl.Krb5HttpClientConfigurer
SOLR_AUTHENTICATION_OPTS="-Djava.security.auth.login.config=/home/foo/jaas-client.conf -Dsolr.kerberos.cookie.domain=192.168.0.107 -Dsolr.kerberos.principal=HTTP/192.168.0.107@EXAMPLE.COM -Dsolr.kerberos.keytab=/keytabs/107.keytab"
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[KerberosAuthenticationPlugin-Step#4:ClientJAASconfiguration]]
Step #4: Client JAAS configuration
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Create the following JAAS file at `/home/foo/jaas-client.conf`. Here, the client principal is same as the service principal. This will be used to authenticate internode requests and requests to Zookeeper. Make sure to put in the right hostname and the keytab file path.

-------------------------------------------------------
Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  keyTab="/keytabs/107.keytab"
  storeKey=true
  useTicketCache=true
  debug=true
  principal="HTTP/192.168.0.107@EXAMPLE.COM";
};
-------------------------------------------------------

[[KerberosAuthenticationPlugin-StartSolr]]
Start Solr
^^^^^^^^^^

Once the configuration is complete, you can start Solr with the `bin/solr` script, customizing the start parameters as appropriate:

-----------------------------
bin/solr -c -z localhost:2181
-----------------------------

[[KerberosAuthenticationPlugin-TesttheConfiguration]]
Test the Configuration
^^^^^^^^^^^^^^^^^^^^^^

1.  Do a `kinit` with your username
2.  Try to access Solr using `curl`. You should get a successful response.
+
-------------------------------------------------------
curl --negotiate -u : "http://192.168.0.107:8983/solr/"
-------------------------------------------------------

Using Hostnames

Note:To use host names instead of IP addresses, use the SOLR_HOST config in bin/solr.in.sh or pass a -Dhost=<hostname> during the Solr startup.

[[KerberosAuthenticationPlugin-UsingSolrJwithaKerberizedSolr]]
Using SolrJ with a Kerberized Solr
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

To use kerberos authentication in a SolrJ application, you need the following two lines before you create a SolrClient.

------------------------------------------------------------------------------------
System.setProperty("java.security.auth.login.config", "/home/foo/jaas-client.conf");
HttpClientUtil.setConfigurer(new Krb5HttpClientConfigurer());
------------------------------------------------------------------------------------

You need to specify a Kerberos principal for the client and a corresponding keytab in the JAAS client configuration file above. Here’s an example:

-------------------------------------------------------
Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  keyTab="/keytabs/foo.keytab"
  storeKey=true
  useTicketCache=true
  debug=true
  principal="foo@EXAMPLE.COM";
};
-------------------------------------------------------
