1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]
3.  link:Using-the-Solr-Administration-User-Interface.html[Using the Solr Administration User Interface]

Logging
-------

The Logging page shows messages from Solr's log files.

When you click the link for "Logging", a page similar to the one below will be displayed:

_The Main Logging Screen, including an example of an error due to a bad document sent by a client_

While this example shows logged messages for only one core, if you have multiple cores in a single instance, they will each be listed, with the level for each.

[[Logging-SelectingaLoggingLevel]]
Selecting a Logging Level
~~~~~~~~~~~~~~~~~~~~~~~~~

When you select the *Level* link on the left, you see the hierarchy of classpaths and classnames for your instance. A row highlighted in yellow indicates that the class has logging capabilities. Click on a highlighted row, and a menu will appear to allow you to change the log level for that class. Characters in boldface indicate that the class will not be affected by level changes to root.

For an explanation of the various logging levels, see link:Configuring-Logging.html[Configuring Logging].
