1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]
3.  link:Legacy-Scaling-and-Distribution.html[Legacy Scaling and Distribution]

Merging Indexes
---------------

If you need to combine indexes from two different projects or from multiple servers previously used in a distributed configuration, you can use either the IndexMergeTool included in `lucene-misc` or the `CoreAdminHandler`.

To merge indexes, they must meet these requirements:

* The two indexes must be compatible: their schemas should include the same fields and they should analyze fields the same way.
* The indexes must not include duplicate data.

Optimally, the two indexes should be built using the same schema.

[[MergingIndexes-UsingIndexMergeTool]]
Using `IndexMergeTool`
~~~~~~~~~~~~~~~~~~~~~~

To merge the indexes, do the following:

1.  Find the lucene-core and lucene-misc JAR files that your version of Solr is using. You can do this by copying your `solr.war` file somewhere and unpacking it (`jar xvf solr.war`). These two JAR files should be in `WEB-INF/lib`. They are probably called something like `lucene-core-VERSION.jar` and `lucene-misc-VERSION.jar`.
2.  Copy them somewhere easy to find.
3.  Make sure that both indexes you want to merge are closed.
4.  Issue this command:
+
--------------------------------------------------------------------------
java -cp /path/to/lucene-core-VERSION.jar:/path/to/lucene-misc-VERSION.jar
 org/apache/lucene/misc/IndexMergeTool
 /path/to/newindex
 /path/to/old/index1
 /path/to/old/index2
--------------------------------------------------------------------------
+
This will create a new index at `/path/to/newindex` that contains both index1 and index2.
5.  Copy this new directory to the location of your application's solr index (move the old one aside first, of course) and start Solr. For example:
+
-----------------------------------------------------------------
java -cp /tmp/lucene-core-4.4.0.jar:
/tmp/lucene-misc-4.4.0.jar org/apache/lucene/misc/IndexMergeTool 
 ./newindex
 ./solr_home/core1/data/index
 ./solr_home/core2/data/index
-----------------------------------------------------------------

[[MergingIndexes-UsingCoreAdmin]]
Using CoreAdmin
~~~~~~~~~~~~~~~

The `MERGEINDEXES` command of the link:CoreAdmin-API.html#CoreAdminAPI-MERGEINDEXES[CoreAdminHandler] can be used to merge indexes into a new core – either from one or more arbitrary `indexDir` directories or by merging from one or more existing `srcCore` core names.

See the link:CoreAdmin-API.html#CoreAdminAPI-MERGEINDEXES[CoreAdminHandler] section for details.
