= Query Syntax and Parsing
:page-shortname: query-syntax-and-parsing
:page-permalink: query-syntax-and-parsing.html
:page-children: common-query-parameters, the-standard-query-parser, the-dismax-query-parser, the-extended-dismax-query-parser, function-queries, local-parameters-in-queries, other-parsers

Solr supports several query parsers, offering search application designers great flexibility in controlling how queries are parsed.

This section explains how to specify the query parser to be used. It also describes the syntax and features supported by the main query parsers included with Solr and describes some other parsers that may be useful for particular situations. There are some query parameters common to all Solr parsers; these are discussed in the section <<common-query-parameters.adoc#,Common Query Parameters>>.

The parsers discussed in this Guide are:

* <<the-standard-query-parser.adoc#,The Standard Query Parser>>
* <<the-dismax-query-parser.adoc#,The DisMax Query Parser>>
* <<the-extended-dismax-query-parser.adoc#,The Extended DisMax Query Parser>>
* <<other-parsers.adoc#,Other Parsers>>

The query parser plugins are all subclasses of http://lucene.apache.org/solr/6_1_0/solr-core/org/apache/solr/search/QParserPlugin.html[QParserPlugin]. If you have custom parsing needs, you may want to extend that class to create your own query parser.

For more detailed information about the many query parsers available in Solr, see https://wiki.apache.org/solr/SolrQuerySyntax.
