= Request Parameters API
:page-shortname: request-parameters-api
:page-permalink: request-parameters-api.html

The Request Parameters API allows creating parameter sets that can override or take the place of parameters defined in `solrconfig.xml`. The parameter sets defined with this API can be used in requests to Solr, or referenced directly in `solrconfig.xml` request handler definitions.

It is really another endpoint of the <<config-api.adoc#,Config API>> instead of a separate API, and has distinct commands. It does not replace or modify any sections of `solrconfig.xml`, but instead provides another approach to handling parameters used in requests. It behaves in the same way as the Config API, by storing parameters in another file that will be used at runtime. In this case, the parameters are stored in a file named `params.json`. This file is kept in ZooKeeper or in the `conf` directory of a standalone Solr instance.

The settings stored in `params.json` are used at query time to override settings defined in `solrconfig.xml` in some cases as described below.

When might you want to use this feature?

* To avoid frequently editing your `solrconfig.xml` to update request parameters that change often.
* To reuse parameters across various request handlers.
* To mix and match parameter sets at request time.
* To avoid a reload of your collection for small parameter changes.

[[RequestParametersAPI-TheRequestParametersEndpoint]]
== The Request Parameters Endpoint

All requests are sent to the `/config/params` endpoint of the Config API.

[[RequestParametersAPI-SettingRequestParameters]]
== Setting Request Parameters

The request to set, unset, or update request parameters is sent as a set of Maps with names. These objects can be directly used in a request or a request handler definition.

The available commands are:

* `set`: Create or overwrite a parameter set map.
* `unset`: delete a parameter set map.
* `update`: update a parameter set map. This is equivalent to a map.putAll(newMap) . Both the maps are merged and if the new map has same keys as old they are overwritten

You can mix these commands into a single request if necessary.

Each map must include a name so it can be referenced later, either in a direct request to Solr or in a request handler definition.

In the following example, we are setting 2 sets of parameters named 'myFacets' and 'myQueries'.

[source,javascript]
----
curl http://localhost:8983/solr/techproducts/config/params -H 'Content-type:application/json'  -d '{
  "set":{
    "myFacets":{
      "facet":"true",
      "facet.limit":5}}, 
  "set":{
    "myQueries":{
      "defType":"edismax",
      "rows":"5",
      "df":"text_all"}}
}'
----

In the above example all the parameters are equivalent to the "defaults" in solrconfig.xml. It is possible to add invariants and appends as follows

[source,javascript]
----
curl http://localhost:8983/solr/techproducts/config/params -H 'Content-type:application/json'  -d '{
  "set":{
    "my_handler_params":{
      "facet.limit":5,      
      "_invariants_": {
        "facet":true,
        "wt":"json"
       },
      "_appends_":{"facet.field":["field1","field2"]
     }
   }}
}'
----

now it is possible to define a request handler as follows

[source,xml]
----
<requestHandler name="/my_handler" class="solr.SearchHandler" useParams="my_handler_params"/>
----

It will be equivalent to a requesthandler definition as follows,

[source,xml]
----
<requestHandler name="/my_handler" class="solr.SearchHandler">
<lst name="defaults">
 <int name="facet.limit">5</int>
</lst>
<lst name="invariants>
  <str name="wt">json</>
  <bool name="facet">true<bool>
</lst>
<lst name="appends">
 <arr name="facet.field">
  <str>field1</str>
  <str>field2</str>
</arr>
</lst>
</requestHandler>
----

Update example,

[source,javascript]
----
curl http://localhost:8983/solr/techproducts/config/params -H 'Content-type:application/json'  -d '{
  "update":{
    "myFacets":{
      "facet.limit":10}}, 
}'
----

This command will add (or replace) the `facet.limit` param to the `myFacets` map, keeping all other existing `myFacets` params.

To see the parameters that have been set, you can use the `/config/params` endpoint to read the contents of `params.json`, or use the name in the request:

[source,bash]
----
curl http://localhost:8983/solr/techproducts/config/params
 
#Or use the params name
curl http://localhost:8983/solr/techproducts/config/params/myQueries
----

[[RequestParametersAPI-TheuseParamsParameter]]
=== The `useParams` Parameter

When making a request, the `useParams` parameter applies the request parameters set to the request. This is translated at request time to the actual params.

For example (using the names we set up in the earlier example, please replace with your own name):

[source,bash]
----
http://localhost/solr/techproducts/select?useParams=myQueries
----

It is possible to pass more than one parameter set in the same request. For example:

[source,bash]
----
http://localhost/solr/techproducts/select?useParams=myFacets,myQueries
----

In the above example the param set 'myQueries' is applied on top of 'myFacets'. So, values in 'myQueries' take precedence over values in 'myFacets'. Additionally, any values passed in the request take precedence over 'useParams' params. This acts like the "defaults" specified in the '`<requestHandler>`' definition in `solrconfig.xml`.

The parameter sets can be used directly in a request handler definition as follows. Please note that the 'useParams' specified is always applied even if the request contains `useParams`.

[source,xml]
----
<requestHandler name="/terms" class="solr.SearchHandler" useParams="myQueries">
  <lst name="defaults">
    <bool name="terms">true</bool>
    <bool name="distrib">false</bool>
  </lst>     
  <arr name="components">
    <str>terms</str>
  </arr>
</requestHandler>
----

To summarize, parameters are applied in this order:

* parameters defined in `<invariants>` in `solrconfig.xml`.
* parameters applied in _invariants_ in params.json and that is specified in the requesthandler definition or even in request
* parameters defined in the request directly.
* parameter sets defined in the request, in the order they have been listed with `useParams`.
* parameter sets defined in `params.json` that have been defined in the request handler.
* parameters defined in `<defaults>` in `solrconfig.xml`.

[[RequestParametersAPI-PublicAPIs]]
=== Public APIs

The RequestParams Object can be accessed using the method `SolrConfig#getRequestParams()`. Each paramset can be accessed by their name using the method `RequestParams#getRequestParams(String name)`.
