= Response Writers
:page-shortname: response-writers
:page-permalink: response-writers.html
:page-children: velocity-response-writer

A Response Writer generates the formatted response of a search. Solr supports a variety of Response Writers to ensure that query responses can be parsed by the appropriate language or application.

The `wt` parameter selects the Response Writer to be used. The table below lists the most common settings for the `wt` parameter.

[width="100%",cols="50%,50%",options="header",]
|===
|`wt` Parameter Setting |Response Writer Selected
|csv |<<ResponseWriters-CSVResponseWriter,CSVResponseWriter>>
|geojson |<<ResponseWriters-GeoJSONResponseWriter,GeoJSONResponseWriter>>
|json |<<ResponseWriters-JSONResponseWriter,JSONResponseWriter>>
|php |<<ResponseWriters-PHPResponseWriterandPHPSerializedResponseWriter,PHPResponseWriter>>
|phps |<<ResponseWriters-PHPResponseWriterandPHPSerializedResponseWriter,PHPSerializedResponseWriter>>
|python |<<ResponseWriters-PythonResponseWriter,PythonResponseWriter>>
|ruby |<<ResponseWriters-RubyResponseWriter,RubyResponseWriter>>
|smile |<<ResponseWriters-SmileResponseWriter,SmileResponseWriter>>
|velocity |<<ResponseWriters-VelocityResponseWriter,VelocityResponseWriter>>
|xml |<<ResponseWriters-TheStandardXMLResponseWriter,XMLResponseWriter>>
|xslt |<<ResponseWriters-TheXSLTResponseWriter,XSLTResponseWriter>>
|===

[[ResponseWriters-TheStandardXMLResponseWriter]]
== The Standard XML Response Writer

The XML Response Writer is the most general purpose and reusable Response Writer currently included with Solr. It is the format used in most discussions and documentation about the response of Solr queries.

Note that the XSLT Response Writer can be used to convert the XML produced by this writer to other vocabularies or text-based formats.

The behavior of the XML Response Writer can be driven by the following query parameters.

[[ResponseWriters-TheversionParameter]]
=== The `version` Parameter

The `version` parameter determines the XML protocol used in the response. Clients are strongly encouraged to _always_ specify the protocol version, so as to ensure that the format of the response they receive does not change unexpectedly if the Solr server is upgraded and a new default format is introduced.

Currently supported version values are:

[width="100%",cols="50%,50%",options="header",]
|===
|XML Version |Notes
|2.2 |The format of the responseHeader changed to use the same `<lst>` structure as the rest of the response.
|===

The default value is the latest supported.

[[ResponseWriters-ThestylesheetParameter]]
=== The `stylesheet` Parameter

The `stylesheet` parameter can be used to direct Solr to include a `<?xml-stylesheet type="text/xsl" href="..."?>` declaration in the XML response it returns.

The default behavior is not to return any stylesheet declaration at all.

[WARNING]
====

Use of the `stylesheet` parameter is discouraged, as there is currently no way to specify external stylesheets, and no stylesheets are provided in the Solr distributions. This is a legacy parameter, which may be developed further in a future release.

====

[[ResponseWriters-TheindentParameter]]
=== The `indent` Parameter

If the `indent` parameter is used, and has a non-blank value, then Solr will make some attempts at indenting its XML response to make it more readable by humans.

The default behavior is not to indent.

[[ResponseWriters-TheXSLTResponseWriter]]
== The XSLT Response Writer

The XSLT Response Writer applies an XML stylesheet to output. It can be used for tasks such as formatting results for an RSS feed.

[[ResponseWriters-trParameter]]
=== `tr` Parameter

The XSLT Response Writer accepts one parameter: the `tr` parameter, which identifies the XML transformation to use. The transformation must be found in the Solr `conf/xslt` directory.

The Content-Type of the response is set according to the `<xsl:output>` statement in the XSLT transform, for example: `<xsl:output media-type="text/html"/>`

[[ResponseWriters-Configuration]]
=== Configuration

The example below, from the `sample_techproducts_configs` <<response-writers.adoc#,config set>> in the Solr distribution, shows how the XSLT Response Writer is configured.

[source,xml]
----
<!--
  Changes to XSLT transforms are taken into account
  every xsltCacheLifetimeSeconds at most.
-->
<queryResponseWriter name="xslt"
                     class="org.apache.solr.request.XSLTResponseWriter">
  <int name="xsltCacheLifetimeSeconds">5</int>
</queryResponseWriter>
----

A value of 5 for `xsltCacheLifetimeSeconds` is good for development, to see XSLT changes quickly. For production you probably want a much higher value.

[[ResponseWriters-JSONResponseWriter]]
== JSON Response Writer

A very commonly used Response Writer is the `JsonResponseWriter`, which formats output in JavaScript Object Notation (JSON), a lightweight data interchange format specified in specified in RFC 4627. Setting the `wt` parameter to `json` invokes this Response Writer.

The default mime type for the JSON writer is `application/json`, however this can be overridden in the `solrconfig.xml` - such as in this example from the "`techproducts`" configuration:

[source,xml]
----
<queryResponseWriter name="json" class="solr.JSONResponseWriter">
  <!-- For the purposes of the tutorial, JSON response are written as
       plain text so that it's easy to read in *any* browser.
       If you are building applications that consume JSON, just remove
       this override to get the default "application/json" mime type.
    -->
  <str name="content-type">text/plain</str>
</queryResponseWriter>
----

[[ResponseWriters-GeoJSONResponseWriter]]
== GeoJSON Response Writer

Returns Solr results in http://geojson.org[GeoJSON] augmented with Solr-specific JSON. To use this, set `wt=geojson` and `geojson.field` to the name of a spatial Solr field. Not all spatial fields types are supported, and you'll get an error if you use an unsupported one.

[[ResponseWriters-PythonResponseWriter]]
== Python Response Writer

Solr has an optional Python response format that extends its JSON output in the following ways to allow the response to be safely evaluated by the python interpreter:

* true and false changed to True and False
* Python unicode strings are used where needed
* ASCII output (with unicode escapes) is used for less error-prone interoperability
* newlines are escaped
* null changed to None

[[ResponseWriters-PHPResponseWriterandPHPSerializedResponseWriter]]
== PHP Response Writer and PHP Serialized Response Writer

Solr has a PHP response format that outputs an array (as PHP code) which can be evaluated. Setting the `wt` parameter to `php` invokes the PHP Response Writer.

Example usage:

[source,java]
----
$code = file_get_contents('http://localhost:8983/solr/techproducts/select?q=iPod&wt=php');
eval("$result = " . $code . ";");
print_r($result);
----

Solr also includes a PHP Serialized Response Writer that formats output in a serialized array. Setting the `wt` parameter to `phps` invokes the PHP Serialized Response Writer.

Example usage:

[source,java]
----
$serializedResult = file_get_contents('http://localhost:8983/solr/techproducts/select?q=iPod&wt=phps');
$result = unserialize($serializedResult);
print_r($result);
----

[[ResponseWriters-RubyResponseWriter]]
== Ruby Response Writer

Solr has an optional Ruby response format that extends its JSON output in the following ways to allow the response to be safely evaluated by Ruby's interpreter:

* Ruby's single quoted strings are used to prevent possible string exploits.
* \ and ' are the only two characters escaped.
* Unicode escapes are not used. Data is written as raw UTF-8.
* nil used for null.
* => is used as the key/value separator in maps.

Here is a simple example of how one may query Solr using the Ruby response format:

[source,java]
----
require 'net/http'
h = Net::HTTP.new('localhost', 8983)
hresp, data = h.get('/solr/techproducts/select?q=iPod&wt=ruby', nil)
rsp = eval(data)
puts 'number of matches = ' + rsp['response']['numFound'].to_s
#print out the name field for each returned document
rsp['response']['docs'].each { |doc| puts 'name field = ' + doc['name'\] }
----

[[ResponseWriters-CSVResponseWriter]]
== CSV Response Writer

The CSV response writer returns a list of documents in comma-separated values (CSV) format. Other information that would normally be included in a response, such as facet information, is excluded.

The CSV response writer supports multi-valued fields, as well as<<transforming-result-documents.adoc#,psuedo-fields>>, and the output of this CSV format is compatible with Solr's https://wiki.apache.org/solr/UpdateCSV[CSV update format].

[[ResponseWriters-CSVParameters]]
=== CSV Parameters

These parameters specify the CSV format that will be returned. You can accept the default values or specify your own.

[width="100%",cols="50%,50%",options="header",]
|===
|Parameter |Default Value
|csv.encapsulator |"
|csv.escape |None
|csv.separator |,
|csv.header |Defaults to true. If false, Solr does not print the column headers
|csv.newline |\n
|csv.null |Defaults to a zero length string. Use this parameter when a document has no value for a particular field.
|===

[[ResponseWriters-Multi-ValuedFieldCSVParameters]]
=== Multi-Valued Field CSV Parameters

These parameters specify how multi-valued fields are encoded. Per-field overrides for these values can be done using `f.<fieldname>.csv.separator=|`.

[width="100%",cols="50%,50%",options="header",]
|===
|Parameter |Default Value
|csv.mv.encapsulator |None
|csv.mv.escape |\
|csv.mv.separator |Defaults to the `csv.separator` value
|===

[[ResponseWriters-Example]]
=== Example

`http://localhost:8983/solr/techproducts/select?q=ipod&fl=id,cat,name,popularity,price,score&wt=csv` returns:

[source,java]
----
id,cat,name,popularity,price,score
IW-02,"electronics,connector",iPod & iPod Mini USB 2.0 Cable,1,11.5,0.98867977
F8V7067-APL-KIT,"electronics,connector",Belkin Mobile Power Cord for iPod w/ Dock,1,19.95,0.6523595
MA147LL/A,"electronics,music",Apple 60 GB iPod with Video Playback Black,10,399.0,0.2446348
----

[[ResponseWriters-VelocityResponseWriter]]
== Velocity Response Writer

The `VelocityResponseWriter` processes the Solr response and request context through Apache Velocity templating.

See <<velocity-response-writer.adoc#,Velocity Response Writer>> section for details.

[[ResponseWriters-BinaryResponseWriter]]
== Binary Response Writer

Solr also includes a Response Writer that outputs binary format for use with a Java client. See <<client-apis.adoc#,Client APIs>> for more details.

[[ResponseWriters-SmileResponseWriter]]
== Smile Response Writer

The Smile format is a JSON-compatible binary format, described in detail here: http://wiki.fasterxml.com/SmileFormat.
