1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]

Solr Glossary
-------------

Where possible, terms are linked to relevant parts of the Solr Reference Guide for more information.

'''''

*Jump to a letter:*

link:#SolrGlossary-A[A] link:#SolrGlossary-B[B] link:#SolrGlossary-C[C] link:#SolrGlossary-D[D] link:#SolrGlossary-E[E] link:#SolrGlossary-F[F] G H link:#SolrGlossary-I[I] J K link:#SolrGlossary-L[L] link:#SolrGlossary-M[M] link:#SolrGlossary-N[N] link:#SolrGlossary-O[O] P link:#SolrGlossary-Q[Q] link:#SolrGlossary-R[R] link:#SolrGlossary-S[S] link:#SolrGlossary-T[T] U V link:#SolrGlossary-W[W] X Y link:#SolrGlossary-Z[Z]

[[SolrGlossary-A]]
A
~

[[SolrGlossary-Atomicupdates]]
link:Updating-Parts-of-Documents.html#UpdatingPartsofDocuments-AtomicUpdates[Atomic updates]

An approach to updating only one or more fields of a document, instead of reindexing the entire document.

[[SolrGlossary-B]]
B
~

[[SolrGlossary-Booleanoperators]]
Boolean operators

These control the inclusion or exclusion of keywords in a query by using operators such as AND, OR, and NOT.

[[SolrGlossary-C]]
C
~

[[SolrGlossary-Cluster]]
Cluster

In Solr, a cluster is a set of Solr nodes managed as a unit. They may contain many cores, collections, shards, and/or replicas. See also link:#SolrGlossary-SolrCloud[#SolrCloud].

[[SolrGlossary-Collection]]
Collection

In Solr, one or more documents grouped together in a single logical index. A collection must have a single schema, but can be spread across multiple cores.

In link:#SolrGlossary-ZooKeeper[#ZooKeeper], a group of cores managed together as part of a SolrCloud installation.

[[SolrGlossary-Commit]]
Commit

To make document changes permanent in the index. In the case of added documents, they would be searchable after a __commit__.

[[SolrGlossary-Core]]
Core

An individual Solr instance (represents a logical index). Multiple cores can run on a single node. See also link:#SolrGlossary-SolrCloud[#SolrCloud].

[[SolrGlossary-Corereload]]
Core reload

To re-initialize Solr after changes to `schema.xml`, `solrconfig.xml` or other configuration files.

[[SolrGlossary-D]]
D
~

[[SolrGlossary-Distributedsearch]]
Distributed search

Distributed search is one where queries are processed across more than one link:#SolrGlossary-Shard[shard].

[[SolrGlossary-Document]]
Document

A group of link:#SolrGlossary-Field[fields] and their values. Documents are the basic unit of data in a link:#SolrGlossary-Collection[collection]. Documents are assigned to link:#SolrGlossary-Shard[shards] using standard hashing, or by specifically assigning a shard within the document ID. Documents are versioned after each write operation.

[[SolrGlossary-E]]
E
~

[[SolrGlossary-Ensemble]]
Ensemble

A link:#SolrGlossary-ZooKeeper[#ZooKeeper] term to indicate multiple ZooKeeper instances running simultaneously.

[[SolrGlossary-F]]
F
~

[[SolrGlossary-Facet]]
Facet

The arrangement of search results into categories based on indexed terms.

[[SolrGlossary-Field]]
Field

The content to be indexed/searched along with metadata defining how the content should be processed by Solr.

[[SolrGlossary-I]]
I
~

[[SolrGlossary-Inversedocumentfrequency(IDF)]]
Inverse document frequency (IDF)

A measure of the general importance of a term. It is calculated as the number of total Documents divided by the number of Documents that a particular word occurs in the collection. See http://en.wikipedia.org/wiki/Tf-idf and http://lucene.apache.org/core/5_3_0/core/org/apache/lucene/search/similarities/TFIDFSimilarity.html[the Lucene TFIDFSimilarity javadocs] for more info on TF-IDF based scoring and Lucene scoring in particular. See also link:#SolrGlossary-Termfrequency[#Term frequency].

[[SolrGlossary-Invertedindex]]
Inverted index

A way of creating a searchable index that lists every word and the documents that contain those words, similar to an index in the back of a book which lists words and the pages on which they can be found. When performing keyword searches, this method is considered more efficient than the alternative, which would be to create a list of documents paired with every word used in each document. Since users search using terms they expect to be in documents, finding the term before the document saves processing resources and time.

[[SolrGlossary-L]]
L
~

[[SolrGlossary-Leader]]
Leader

The main node for each shard that routes document adds, updates, or deletes to other replicas in the same shard - this is a transient responsibility assigned to a node via an election, if the current Shard Leader goes down, a new node will be elected to take it's place. See also link:#SolrGlossary-SolrCloud[#SolrCloud].

[[SolrGlossary-M]]
M
~

[[SolrGlossary-Metadata]]
Metadata

Literally, __data about data__. Metadata is information about a document, such as it's title, author, or location.

[[SolrGlossary-N]]
N
~

[[SolrGlossary-Naturallanguagequery]]
Natural language query

A search that is entered as a user would normally speak or write, as in, "What is aspirin?"

[[SolrGlossary-Node]]
Node

A JVM instance running Solr. Also known as a Solr server.

[[SolrGlossary-O]]
O
~

[[SolrGlossary-Optimisticconcurrency]]
link:Updating-Parts-of-Documents.html#UpdatingPartsofDocuments-OptimisticConcurrency[Optimistic concurrency]

Also known as "optimistic locking", this is an approach that allows for updates to documents currently in the index while retaining locking or version control.

[[SolrGlossary-Overseer]]
Overseer

A single node in SolrCloud that is responsible for processing actions involving the entire cluster. It keeps track of the state of existing nodes and shards, and assigns shards to nodes - this is a transient responsibility assigned to a node via an election, if the current Overseer goes down, a new node will be elected to take it's place. See also link:#SolrGlossary-SolrCloud[#SolrCloud].

[[SolrGlossary-Q]]
Q
~

[[SolrGlossary-Queryparser]]
Query parser

A query parser processes the terms entered by a user.

[[SolrGlossary-R]]
R
~

[[SolrGlossary-Recall]]
Recall

The ability of a search engine to retrieve _all_ of the possible matches to a user's query.

[[SolrGlossary-Relevance]]
Relevance

The appropriateness of a document to the search conducted by the user.

[[SolrGlossary-Replica]]
Replica

A copy of a shard or single logical index, for use in failover or load balancing.

[[SolrGlossary-Replication]]
link:Index-Replication.html[Replication]

A method of copying a master index from one server to one or more "slave" or "child" servers.

[[SolrGlossary-RequestHandler]]
link:RequestHandlers-and-SearchComponents-in-SolrConfig.html[RequestHandler]

Logic and configuration parameters that tell Solr how to handle incoming "requests", whether the requests are to return search results, to index documents, or to handle other custom situations.

[[SolrGlossary-S]]
S
~

[[SolrGlossary-SearchComponent]]
link:RequestHandlers-and-SearchComponents-in-SolrConfig.html[SearchComponent]

Logic and configuration parameters used by request handlers to process query requests. Examples of search components include faceting, highlighting, and "more like this" functionality.

[[SolrGlossary-Shard]]
Shard

In SolrCloud, a logical section of a single collection. This may be spread across multiple nodes. See also link:#SolrGlossary-SolrCloud[#SolrCloud].

[[SolrGlossary-SolrCloudSolrCloud_32604293.html]]
link:SolrCloud.html[SolrCloud]

Umbrella term for a suite of functionality in Solr which allows managing a cluster of Solr servers for scalability, fault tolerance, and high availability.

[[SolrGlossary-SolrSchema(schema.xml)]]
Solr Schema (schema.xml)

The Apache Solr index schema. The schema defines the fields to be indexed and the type for the field (text, integers, etc.) The schema is stored in schema.xml and is located in the Solr home conf directory.

[[SolrGlossary-SolrConfig(solrconfig.xml)]]
SolrConfig (solrconfig.xml)

The Apache Solr configuration file. Defines indexing options, RequestHandlers, highlighting, spellchecking and various other configurations. The file, solrconfig.xml is located in the Solr home conf directory.

[[SolrGlossary-SpellCheck]]
Spell Check

The ability to suggest alternative spellings of search terms to a user, as a check against spelling errors causing few or zero results.

[[SolrGlossary-Stopwords]]
Stopwords

Generally, words that have little meaning to a user's search but which may have been entered as part of a link:#SolrGlossary-Naturallanguagequery[natural language] query. Stopwords are generally very small pronouns, conjunctions and prepositions (such as, "the", "with", or "and")

[[SolrGlossary-SuggesterSuggester_32604262.html]]
link:Suggester.html[Suggester]

Functionality in Solr that provides the ability to suggest possible query terms to users as they type.

[[SolrGlossary-Synonyms]]
Synonyms

Synonyms generally are terms which are near to each other in meaning and may substitute for one another. In a search engine implementation, synonyms may be abbreviations as well as words, or terms that are not consistently hyphenated. Examples of synonyms in this context would be "Inc." and "Incorporated" or "iPod" and "i-pod".

[[SolrGlossary-T]]
T
~

[[SolrGlossary-Termfrequency]]
Term frequency

The number of times a word occurs in a given document. See http://en.wikipedia.org/wiki/Tf-idf and http://lucene.apache.org/core/5_3_0/core/org/apache/lucene/search/similarities/TFIDFSimilarity.html[the Lucene TFIDFSimilarity javadocs] for more info on TF-IDF based scoring and Lucene scoring in particular. See also link:#SolrGlossary-Inversedocumentfrequency(IDF)[#Inverse document frequency (IDF)].

[[SolrGlossary-Transactionlog]]
Transaction log

An append-only log of write operations maintained by each node. This log is only required with SolrCloud implementations and is created and managed automatically by Solr.

[[SolrGlossary-W]]
W
~

[[SolrGlossary-Wildcard]]
Wildcard

A wildcard allows a substitution of one or more letters of a word to account for possible variations in spelling or tenses.

[[SolrGlossary-Z]]
Z
~

[[SolrGlossary-ZooKeeper]]
ZooKeeper

Also known as http://zookeeper.apache.org/[Apache ZooKeeper]. The system used by SolrCloud to keep track of configuration files and node names for a cluster. A ZooKeeper cluster is used as the central configuration store for the cluster, a coordinator for operations requiring distributed synchronization, and the system of record for cluster topology. See also link:#SolrGlossary-SolrCloud[#SolrCloud].
