Solr JDBC - DbVisualizer
========================
:toc:
:page-shortname: solr-jdbc-dbvisualizer
:page-permalink: solr-jdbc-dbvisualizer.html

toc::[]

For https://www.dbvis.com/[DbVisualizer], you will need to create a new driver for Solr using the DbVisualizer Driver Manager. This will add several SolrJ client .jars to the DbVisualizer classpath. The files required are:

* all .jars found in `$SOLR_HOME/dist/solrj-lib`
* the SolrJ .jar found at `$SOLR_HOME/dist/solr-solrj-<version>.jar`

Once the driver has been created, you can create a connection to Solr with the connection string format outlined in the generic section and use the SQL Commander to issue queries.

[[SolrJDBC-DbVisualizer-SetupDriver]]
== Setup Driver

[[SolrJDBC-DbVisualizer-OpenDriverManager]]
=== Open Driver Manager

From the Tools menu, choose Driver Manager to add a driver.

[[SolrJDBC-DbVisualizer-CreateaNewDriver]]
=== Create a New Driver

[[SolrJDBC-DbVisualizer-NametheDriver]]
=== Name the Driver

Provide a name for the driver, and provide the URL format: `jdbc:solr://<zk_connection_string>/?collection=<collection>`. Do not fill in values for the variables "`zk_connection_string`" and "`collection`", those will be provided later when the connection to Solr is configured. The Driver Class will also be automatically added when the driver .jars are added.

[[SolrJDBC-DbVisualizer-AddDriverFilestoClasspath]]
=== Add Driver Files to Classpath

The driver files to be added are:

* all .jars in `$SOLR_HOME/dist/solrj-lib`
* the SolrJ .jar found in `$SOLR_HOME/dist/solr-solrj-<version>.jar`

[[SolrJDBC-DbVisualizer-ReviewandCloseDriverManager]]
=== Review and Close Driver Manager

Once the driver files have been added, you can close the Driver Manager.

[[SolrJDBC-DbVisualizer-CreateaConnection]]
== Create a Connection

Next, create a connection to Solr using the driver just created.

[[SolrJDBC-DbVisualizer-UsetheConnectionWizard]]
=== Use the Connection Wizard

[[SolrJDBC-DbVisualizer-NametheConnection]]
=== Name the Connection

[[SolrJDBC-DbVisualizer-SelecttheSolrdriver]]
=== Select the Solr driver

[[SolrJDBC-DbVisualizer-SpecifytheSolrURL]]
=== Specify the Solr URL

Provide the Solr URL, using the ZooKeeper host and port and the collection. For example, `jdbc:solr://localhost:9983?collection=test`

[[SolrJDBC-DbVisualizer-OpenandConnecttoSolr]]
== Open and Connect to Solr

Once the connection has been created, double-click on it to open the connection details screen and connect to Solr.

[[SolrJDBC-DbVisualizer-OpenSQLCommandertoEnterQueries]]
== Open SQL Commander to Enter Queries

When the connection is established, you can use the SQL Commander to issue queries and view data.
