1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]
3.  link:The-Well-Configured-Solr-Instance.html[The Well-Configured Solr Instance]

Solr Cores and solr.xml
-----------------------

In Solr, the term _core_ is used to refer to a single index and associated transaction log and configuration files (including `schema.xml` and `solrconfig.xml`, among others). Your Solr installation can have multiple cores if needed, which allows you to index data with different structures in the same server, and maintain more control over how your data is presented to different audiences. In SolrCloud mode you will be more familiar with the term __collection.__ Behind the scenes a collection consists of one or more cores.

Cores can be created using `bin/solr` script or as part of SolrCloud collection creation using the APIs. Core-specific properties (such as the directories to use for the indexes or configuration files, the core name, and other options) are defined in a `core.properties` file. Any `core.properties` file in any directory of your Solr installation (or in a directory under where `solr_home` is defined) will be found by Solr and the defined properties will be used for the core named in the file.

In standalone mode, `solr.xml` must reside in `solr_home`. In SolrCloud mode, `solr.xml` will be loaded from Zookeeper if it exists, with fallback to `solr_home`.

Note:

In older versions of Solr, cores had to be predefined as `<core>` tags in `solr.xml` in order for Solr to know about them. Now, however, Solr supports automatic discovery of cores and they no longer need to be explicitly defined. The recommended way is to dynamically create cores/collections using the APIs.

The following sections describe these options in more detail.

* **link:Format-of-solr.xml.html[Format of solr.xml]**: Details on how to define `solr.xml`, including the acceptable parameters for the `solr.xml` file
* **link:Defining-core.properties.html[Defining core.properties]**: Details on placement of `core.properties` and available property options.
* **link:CoreAdmin-API.html[CoreAdmin API]**: Tools and commands for core administration using a REST API.
* **link:Config-Sets.html[Config Sets]**: How to use configsets to avoid duplicating effort when defining a new core.

