1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]

The Well Configured Solr Instance
---------------------------------

This section tells you how to fine-tune your Solr instance for optimum performance. This section covers the following topics:

link:Configuring-solrconfig.xml.html[Configuring solrconfig.xml]: Describes how to work with the main configuration file for Solr, `solrconfig.xml`, covering the major sections of the file.

link:Solr-Cores-and-solr.xml.html[Solr Cores and solr.xml]: Describes how to work with `solr.xml` and `core.properties` to configure your Solr core, or multiple Solr cores within a single instance.

link:Solr-Plugins.html[Solr Plugins]: Introduces Solr plugins with pointers to more information.

link:JVM-Settings.html[JVM Settings]: Gives some guidance on best practices for working with Java Virtual Machines.

Note:

The focus of this section is generally on configuring a single Solr instance, but for those interested in scaling a Solr implementation in a cluster environment, see also the section link:SolrCloud.html[SolrCloud]. There are also options to scale through sharding or replication, described in the section link:Legacy-Scaling-and-Distribution.html[Legacy Scaling and Distribution].
