1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]
3.  link:Searching.html[Searching]

The Term Vector Component
-------------------------

The TermVectorComponent is a search component designed to return additional information about documents matching your search.

For each document in the response, the TermVectorCcomponent can return the term vector, the term frequency, inverse document frequency, position, and offset information.

[[TheTermVectorComponent-Configuration]]
Configuration
~~~~~~~~~~~~~

The TermVectorComponent is not enabled implicitly in Solr - it must be explicitly configured in your `solrconfig.xml` file. The examples on this page show how it is configured in Solr's "`techproducts`" example:

------------------------
bin/solr -e techproducts
------------------------

To enable the this component, you need to configure it using a `searchComponent` element:

---------------------------------------------------------------------------------------------------
<searchComponent name="tvComponent" class="org.apache.solr.handler.component.TermVectorComponent"/>
---------------------------------------------------------------------------------------------------

A request handler must then be configured to use this component name. In this example, the component is associated with a special request handler named `/tvrh`, that enables term vectors by default using the `tv=true` parameter; but you can associate it with any request handler:

-------------------------------------------------------------------------------------
<requestHandler name="/tvrh" class="org.apache.solr.handler.component.SearchHandler">
  <lst name="defaults">
    <bool name="tv">true</bool>
  </lst>
  <arr name="last-components">
    <str>tvComponent</str>
  </arr>
</requestHandler>
-------------------------------------------------------------------------------------

Once your handler is defined, you may use it to fetch term vectors for any fields configured with the `termVector` attribute in your `schema.xml`, for example:

----------------------------
<field name="includes"
       type="text"
       indexed="true"
       stored="true"
       multiValued="true"
       termVectors="true"
       termPositions="true"
       termOffsets="true" />
----------------------------

[[TheTermVectorComponent-InvokingtheTermVectorComponent]]
Invoking the Term Vector Component
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The example below shows an invocation of this component using the above configuration:

` http://localhost:8983/solr/techproducts/tvrh?q=*%3A*&start=0&rows=10&fl=id,includes `

------------------------------------------
...
<lst name="termVectors">
   <lst name="warnings">
     <arr name="noTermVectors">
       <str>id</str>
     </arr>
   </lst>
   <lst name="doc-5">
     <str name="uniqueKey">MA147LL/A</str>
     <lst name="includes">
       <lst name="cabl"/>
       <lst name="earbud"/>
       <lst name="headphon"/>
       <lst name="usb"/>
     </lst>
   </lst>
   <str name="uniqueKeyFieldName">id</str>
   <lst name="doc-9">
     <str name="uniqueKey">3007WFP</str>
     <lst name="includes">
       <lst name="cabl"/>
       <lst name="usb"/>
     </lst>
   </lst>
   <str name="uniqueKeyFieldName">id</str>
   <lst name="doc-12">
     <str name="uniqueKey">9885A004</str>
     <lst name="includes">
       <lst name="32"/>
       <lst name="av"/>
       <lst name="batteri"/>
       <lst name="cabl"/>
       <lst name="card"/>
       <lst name="mb"/>
       <lst name="sd"/>
       <lst name="usb"/>
     </lst>
   </lst>
   <str name="uniqueKeyFieldName">id</str>
 </lst>
------------------------------------------

[[TheTermVectorComponent-RequestParameters]]
Request Parameters
^^^^^^^^^^^^^^^^^^

The example below shows the available request parameters for this component:

`http://localhost:8983/solr/techproducts/tvrh?q=includes:[* TO *]&rows=10&indent=true&tv=true&tv.tf=true&tv.df=true&tv.positions=true&tv.offsets=true&tv.payloads=true&tv.fl=includes`

[width="100%",cols="34%,33%,33%",options="header",]
|===================================================================================================================================================================================================
|Boolean Parameters |Description |Type
|tv |Should the component run or not |boolean
|tv.docIds |Returns term vectors for the specified list of Lucene document IDs (not the Solr Unique Key). |comma seperated integers
|tv.fl |Returns term vectors for the specified list of fields. If not specified, the `fl` parameter is used. |comma seperated list of field names
|tv.all |A shortcut that invokes all the boolean parameters listed below. |boolean
|tv.df |Returns the Document Frequency (DF) of the term in the collection. This can be computationally expensive. |boolean
|tv.offsets |Returns offset information for each term in the document. |boolean
|tv.positions |Returns position information. |boolean
|tv.payloads |Returns payload information. |boolean
|tv.tf |Returns document term frequency info per term in the document. |boolean
|tv.tf_idf |Calculates TF*IDF for each term. Requires the parameters `tv.tf` and `tv.df` to be "true". This can be computationally expensive. (The results are not shown in example output) |boolean
|===================================================================================================================================================================================================

To learn more about TermVector component output, see the Wiki page: http://wiki.apache.org/solr/TermVectorComponentExampleOptions

For schema requirements, see the Wiki page: http://wiki.apache.org/solr/FieldOptionsByUseCase

[[TheTermVectorComponent-SolrJandtheTermVectorComponent]]
SolrJ and the Term Vector Component
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Neither the SolrQuery class nor the QueryResponse class offer specific method calls to set Term Vector Component parameters or get the "termVectors" output. However, there is a patch for it: https://issues.apache.org/jira/browse/SOLR-949[SOLR-949].
