= Using ZooKeeper to Manage Configuration Files
:page-shortname: using-zookeeper-to-manage-configuration-files
:page-permalink: using-zookeeper-to-manage-configuration-files.html

With SolrCloud your configuration files are kept in ZooKeeper. These files are uploaded in either of the following cases:

* When you start a SolrCloud example using the `bin/solr` script.
* When you create a collection using the `bin/solr` script.
* Explicitly upload a configuration set to ZooKeeper.

[[UsingZooKeepertoManageConfigurationFiles-StartupBootstrap]]
== Startup Bootstrap

When you try SolrCloud for the first time using the `bin/solr -e cloud`, the related configset gets uploaded to zookeeper automatically and is linked with the newly created collection.

The below command would start SolrCloud with the default collection name (gettingstarted) and default configset (data_driven_schema_configs) uploaded and linked to it.

[source,java]
----
$ bin/solr -e cloud -noprompt
----

You can also explicitly upload a configuration directory when creating a collection using the `bin/solr` script with the `-d` option, such as:

[source,java]
----
$ bin/solr create -c mycollection -d data_driven_schema_configs
----

The create command will upload a copy of the `data_driven_schema_configs` configuration directory to ZooKeeper under `/configs/mycollection`. Refer to the <<solr-start-script-reference.adoc#,Solr Start Script Reference>> page for more details about the create command for creating collections.

Once a configuration directory has been uploaded to ZooKeeper, you can update them using the <<command-line-utilities.adoc#,ZooKeeper Command Line Interface (zkCLI)>>.

Note:

It's a good idea to keep these files under version control.

[[UsingZooKeepertoManageConfigurationFiles-UploadingconfigsusingzkcliorSolrJ]]
== Uploading configs using zkcli or SolrJ

In production situations, <<config-sets.adoc#,Config Sets>> can also be uploaded to ZooKeeper independent of collection creation using either Solr's <<command-line-utilities.adoc#,zkcli.sh script,>> or the http://lucene.apache.org/solr/6_1_0/solr-solrj/org/apache/solr/client/solrj/impl/CloudSolrClient.html#uploadConfig(java.nio.file.Path,java.lang.String)[CloudSolrClient.uploadConfig] java method.

The below command can be used to upload a new configset using the zkcli script.

[source,java]
----
$  sh zkcli.sh -cmd upconfig -zkhost  <host:port> -confname <name for configset> -solrhome <solrhome> -confdir <path to directory with configset>
----

More information about the ZooKeeper Command Line Utility to help manage changes to configuration files, can be found in the section on <<command-line-utilities.adoc#,Command Line Utilities>>.

[[UsingZooKeepertoManageConfigurationFiles-ManagingYourSolrCloudConfigurationFiles]]
== Managing Your SolrCloud Configuration Files

To update or change your SolrCloud configuration files:

1.  Download the latest configuration files from ZooKeeper, using the source control checkout process.
2.  Make your changes.
3.  Commit your changed file to source control.
4.  Push the changes back to ZooKeeper.
5.  Reload the collection so that the changes will be in effect.

[[UsingZooKeepertoManageConfigurationFiles-PreparingZooKeeperbeforefirstclusterstart]]
== Preparing ZooKeeper before first cluster start

If you will share the same ZooKeeper instance with other applications you should use a _chroot_ in ZooKeeper. Please see <<taking-solr-to-production.adoc#TakingSolrtoProduction-ZooKeeperchroot,Taking Solr to Production#ZooKeeperchroot>> for instructions.

There are certain configuration files containing cluster wide configuration. Since some of these are crucial for the cluster to function properly, you may need to upload such files to ZooKeeper before starting your Solr cluster for the first time. Examples of such configuration files (not exhaustive) are `solr.xml`, `security.json `and `clusterprops.json`.

If you for example would like to keep your `solr.xml` in ZooKeeper to avoid having to copy it to every node's `solr_home` directory, you can push it to ZooKeeper with the `zkcli.sh` utility (Unix example):

[source,text]
----
zkcli.sh -zkhost localhost:2181 -cmd putfile /solr.xml /path/to/solr.xml
----
