1.  link:index.html[Apache Solr Reference Guide]
2.  link:Apache-Solr-Reference-Guide.html[Apache Solr Reference Guide]
3.  link:SolrCloud.html[SolrCloud]
4.  link:SolrCloud-Configuration-and-Parameters.html[SolrCloud Configuration and Parameters]

ZooKeeper Access Control
------------------------

This section describes using ZooKeeper access control lists (ACLs) with Solr. For information about ZooKeeper ACLs, see the ZooKeeper documentation at http://zookeeper.apache.org/doc/r3.4.6/zookeeperProgrammers.html#sc_ZooKeeperAccessControl.

* link:#ZooKeeperAccessControl-AboutZooKeeperACLs[About ZooKeeper ACLs]
* link:#ZooKeeperAccessControl-HowtoEnableACLs[How to Enable ACLs]
* link:#ZooKeeperAccessControl-ExampleUsages[Example Usages]

[[ZooKeeperAccessControl-AboutZooKeeperACLs]]
About ZooKeeper ACLs
~~~~~~~~~~~~~~~~~~~~

SolrCloud uses ZooKeeper for shared information and for coordination.

This section describes how to configure Solr to add more restrictive ACLs to the ZooKeeper content it creates, and how to tell Solr about the credentials required to access the content in ZooKeeper. If you want to use ACLs in your ZooKeeper nodes, you will have to activate this functionality; by default, Solr behavior is open-unsafe ACL everywhere and uses no credentials.

Changing Solr-related content in ZooKeeper might damage a SolrCloud cluster. For example:

* Changing configuration might cause Solr to fail or behave in an unintended way.
* Changing cluster state information into something wrong or inconsistent might very well make a SolrCloud cluster behave strangely.
* Adding a delete-collection job to be carried out by the Overseer will cause data to be deleted from the cluster.

You may want to enable ZooKeeper ACLs with Solr if you grant access to your ZooKeeper ensemble to entities you do not trust, or if you want to reduce risk of bad actions resulting from, e.g.:

* Malware that found its way into your system.
* Other systems using the same ZooKeeper ensemble (a "bad thing" might be done by accident).

You might even want to limit read-access, if you think there is stuff in ZooKeeper that not everyone should know about. Or you might just in general work on need-to-know-basis.

Protecting ZooKeeper itself could mean many different things. **This section is about protecting Solr content in ZooKeeper**. ZooKeeper content basically lives persisted on disk and (partly) in memory of the ZooKeeper processes. *This section is not about protecting ZooKeeper data at storage or ZooKeeper process levels* - that's for ZooKeeper to deal with.

But this content is also available to "the outside" via the ZooKeeper API. Outside processes can connect to ZooKeeper and create/update/delete/read content; for example, a Solr node in a SolrCloud cluster wants to create/update/delete/read, and a SolrJ client wants to read from the cluster. It is the responsibility of the outside processes that create/update content to setup ACLs on the content. ACLs describe who is allowed to read, update, delete, create, etc. Each piece of information (znode/content) in ZooKeeper has its own set of ACLs, and inheritance or sharing is not possible. The default behavior in Solr is to add one ACL on all the content it creates - one ACL that gives anyone the permission to do anything (in ZooKeeper terms this is called "the open-unsafe ACL").

[[ZooKeeperAccessControl-HowtoEnableACLs]]
How to Enable ACLs
~~~~~~~~~~~~~~~~~~

We want to be able to:

1.  Control the credentials Solr uses for its ZooKeeper connections. The credentials are used to get permission to perform operations in ZooKeeper.
2.  Control which ACLs Solr will add to znodes (ZooKeeper files/folders) it creates in ZooKeeper.
3.  Control it "from the outside", so that you do not have to modify and/or recompile Solr code to turn this on.

Solr nodes, clients and tools (e.g. ZkCLI) always use a java class called http://lucene.apache.org/solr/5_3_0/solr-solrj/org/apache/solr/common/cloud/SolrZkClient.html[`SolrZkClient`] to deal with their ZooKeeper stuff. The implementation of the solution described here is all about changing `SolrZkClient`. If you use `SolrZkClient` in your application, the descriptions below will be true for your application too.

[[ZooKeeperAccessControl-ControllingCredentials]]
Controlling Credentials
^^^^^^^^^^^^^^^^^^^^^^^

You control which credentials provider will be used by configuring the `zkCredentialsProvider` property in `solr.xml`'s `<solrcloud>` section to the name of a class (on the classpath) implementing the following interface:

------------------------------------------------------
package org.apache.solr.common.cloud;
public interface ZkCredentialsProvider {
  public class ZkCredentials {
    String scheme;
    byte[] auth;

    public ZkCredentials(String scheme, byte[] auth) {
      super();
      this.scheme = scheme;
      this.auth = auth;
    }
    String getScheme() {
      return scheme;
    }
    byte[] getAuth() {
      return auth;
    }
  }
  Collection<ZkCredentials> getCredentials();
}
------------------------------------------------------

Solr determines which credentials to use by calling the `getCredentials()` method of the given credentials provider. If no provider has been configured, the default implementation, `DefaultZkCredentialsProvider` is used..

[[ZooKeeperAccessControl-OutoftheBoxImplementations]]
Out of the Box Implementations
++++++++++++++++++++++++++++++

You can always make you own implementation, but Solr comes with:

* `org.apache.solr.common.cloud.DefaultZkCredentialsProvider `

Its `getCredentials()` returns a list of length zero - no credentials used. This is the default and is used if you do not configure a provider in `solr.xml`.

* `org.apache.solr.common.cloud.VMParamsSingleSetCredentialsDigestZkCredentialsProvider`

This one lets you define your credentials using system properties. It supports at most one set of credentials.

* ** The schema is "digest". The username and password are defined by system properties "`zkDigestUsername`" and "`zkDigestPassword`", respectively. This set of credentials will be added to the list of credentials returned by `getCredentials()` if both username and password are provided.
** If the one set of credentials above is not added to the list, this implementation will fall back to default behavior and use the (empty) credentials list from `DefaultZkCredentialsProvider`.

[[ZooKeeperAccessControl-ControllingACLs]]
Controlling ACLs
^^^^^^^^^^^^^^^^

You control which ACLs will be added by configuring `zkACLProvider` property in `solr.xml`'s `<solrcloud>` section to the name of a class (on the classpath) implementing the following interface:

-------------------------------------------
package org.apache.solr.common.cloud;

public interface ZkACLProvider {
  List<ACL> getACLsToAdd(String zNodePath);
}
-------------------------------------------

When solr wants to create a new znode, it determines which ACLs to put on the znode by calling the `getACLsToAdd()` method of the given acl provider. If no provider has been configured, the default implementation, `DefaultZkACLProvider` is used.

[[ZooKeeperAccessControl-OutoftheBoxImplementations.1]]
Out of the Box Implementations
++++++++++++++++++++++++++++++

You can always make you own implementation, but Solr comes with:

* `org.apache.solr.common.cloud.DefaultZkACLProvider`

It returns a list of length one for all `zNodePath`-s. The single ACL entry in the list is "open-unsafe". This is the default and is used if you do not configure a provider in `solr.xml`.

* `org.apache.solr.common.cloud.VMParamsAllAndReadonlyDigestZkACLProvider`

This one lets you define your ACLs using system properties. Its `getACLsToAdd()` implementation does not use `zNodePath` for anything, so all znodes will get the same set of ACLs. It supports adding one or both of:

* ** *** A user that is allowed to do everything.
**** The permission is "`ALL`" (corresponding to all of `CREATE`, `READ`, `WRITE`, `DELETE` and `ADMIN`), and the schema is "digest". The username and password are defined by system properties "`zkDigestUsername`" and "`zkDigestPassword`", respectively. This ACL will not be added to the list of ACLs unless both username and password are provided.
*** A user that is only allowed to perform read operations.
**** The permission is "`READ`" and the schema is "digest". The username and password are defined by system properties "`zkDigestReadonlyUsername`" and "`zkDigestReadonlyPassword`", respectively. This ACL will not be added to the list of ACLs unless both username and password are provided.

If neither of the above ACLs is added to the list, the (empty) ACL list of `DefaultZkACLProvider` will be used by default.

Notice the overlap in system property names with credentials provider `VMParamsSingleSetCredentialsDigestZkCredentialsProvider` (described above). This is to let the two providers collaborate in a nice and perhaps common way: we always protect access to content by limiting to two users - an admin-user and a readonly-user - AND we always connect with credentials corresponding to this same admin-user, basically so that we can do anything to the content/znodes we create ourselves.

You can give the readonly credentials to "clients" of your SolrCloud cluster - e.g. to be used by SolrJ clients. They will be able to read whatever is necessary to run a functioning SolrJ client, but they will not be able to modify any content in ZooKeeper.

[[ZooKeeperAccessControl-ExampleUsages]]
Example Usages
~~~~~~~~~~~~~~

Let's say that you want all Solr-related content in ZooKeeper protected. You want an "admin" user that is able to do anything to the content in ZooKeeper - this user will be used for initializing Solr content in ZooKeeper and for server-side Solr nodes. You also want a "readonly" user that is only able to read content from ZooKeeper - this user will be handed over to "clients".

In the examples below:

* The "admin" user's username/password is admin-user/admin-password.
* The "readonly" user's username/password is readonly-user/readonly-password.

The provider class names must first be configured in `solr.xml`:

---------------------------------------------------------------------------------------------------------------------------------
...
<solrcloud>
...
    <str name="zkCredientialsProvider">org.apache.solr.common.cloud.VMParamsSingleSetCredentialsDigestZkCredentialsProvider</str>
    <str name="zkACLProvider">org.apache.solr.common.cloud.VMParamsAllAndReadonlyDigestZkACLProvider</str>
---------------------------------------------------------------------------------------------------------------------------------

[[ZooKeeperAccessControl-TouseZkCLI:]]
To use ZkCLI:
+++++++++++++

-----------------------------------------------------------------------------------------
SOLR_ZK_CREDS_AND_ACLS="-DzkDigestUsername=admin-user -DzkDigestPassword=admin-password \
-DzkDigestReadonlyUsername=readonly-user -DzkDigestReadonlyPassword=readonly-password"

java ... $SOLR_ZK_CREDS_AND_ACLS ... org.apache.solr.cloud.ZkCLI -cmd ...
-----------------------------------------------------------------------------------------

[[ZooKeeperAccessControl-Foroperationsusingbin/solr,addthefollowingatthebottomofbin/solr.in.sh:]]
For operations using `bin/solr`, add the following at the bottom of `bin/solr.in.sh`:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

-----------------------------------------------------------------------------------------
SOLR_ZK_CREDS_AND_ACLS="-DzkDigestUsername=admin-user -DzkDigestPassword=admin-password \
-DzkDigestReadonlyUsername=readonly-user -DzkDigestReadonlyPassword=readonly-password"

SOLR_OPTS="$SOLR_OPTS $SOLR_ZK_CREDS_AND_ACLS"
-----------------------------------------------------------------------------------------

[[ZooKeeperAccessControl-Foroperationsusingbin\solr.cmd,addthefollowingatthebottomofbin\solr.in.cmd:]]
For operations using `bin\solr.cmd`, add the following at the bottom of `bin\solr.in.cmd`:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

--------------------------------------------------------------------------------------------
set SOLR_ZK_CREDS_AND_ACLS=-DzkDigestUsername=admin-user -DzkDigestPassword=admin-password ^
-DzkDigestReadonlyUsername=readonly-user -DzkDigestReadonlyPassword=readonly-password

set SOLR_OPTS=%SOLR_OPTS% %SOLR_ZK_CREDS_AND_ACLS%
--------------------------------------------------------------------------------------------

[[ZooKeeperAccessControl-Tostartyourown"clients"(usingSolrJ):]]
To start your own "clients" (using SolrJ):
++++++++++++++++++++++++++++++++++++++++++

----------------------------------------------------------------------------------------------
SOLR_ZK_CREDS_AND_ACLS="-DzkDigestUsername=readonly-user -DzkDigestPassword=readonly-password"

java ... $SOLR_ZK_CREDS_AND_ACLS ... 
----------------------------------------------------------------------------------------------

Or since you yourself are writing the code creating the `SolrZkClient`-s, you might want to override the provider implementations at the code level instead.
